import type { QuizQuestion } from "@/features/cards/quiz/quizBank";
// Extra university bank: 150 domande
export const QUIZ_BANK_PHARMACOLOGY_EXTRA: QuizQuestion[] = [
  {
    id: "uni_ph_0501",
    q: "[Farmacologia] Domanda 501: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0502",
    q: "[Farmacologia] Domanda 502: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0503",
    q: "[Farmacologia] Domanda 503: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0504",
    q: "[Farmacologia] Domanda 504: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0505",
    q: "[Farmacologia] Domanda 505: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0506",
    q: "[Farmacologia] Domanda 506: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0507",
    q: "[Farmacologia] Domanda 507: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0508",
    q: "[Farmacologia] Domanda 508: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0509",
    q: "[Farmacologia] Domanda 509: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0510",
    q: "[Farmacologia] Domanda 510: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0511",
    q: "[Farmacologia] Domanda 511: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0512",
    q: "[Farmacologia] Domanda 512: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0513",
    q: "[Farmacologia] Domanda 513: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0514",
    q: "[Farmacologia] Domanda 514: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0515",
    q: "[Farmacologia] Domanda 515: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0516",
    q: "[Farmacologia] Domanda 516: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0517",
    q: "[Farmacologia] Domanda 517: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0518",
    q: "[Farmacologia] Domanda 518: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0519",
    q: "[Farmacologia] Domanda 519: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0520",
    q: "[Farmacologia] Domanda 520: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0521",
    q: "[Farmacologia] Domanda 521: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0522",
    q: "[Farmacologia] Domanda 522: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0523",
    q: "[Farmacologia] Domanda 523: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0524",
    q: "[Farmacologia] Domanda 524: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0525",
    q: "[Farmacologia] Domanda 525: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0526",
    q: "[Farmacologia] Domanda 526: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0527",
    q: "[Farmacologia] Domanda 527: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0528",
    q: "[Farmacologia] Domanda 528: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0529",
    q: "[Farmacologia] Domanda 529: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0530",
    q: "[Farmacologia] Domanda 530: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0531",
    q: "[Farmacologia] Domanda 531: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0532",
    q: "[Farmacologia] Domanda 532: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0533",
    q: "[Farmacologia] Domanda 533: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0534",
    q: "[Farmacologia] Domanda 534: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0535",
    q: "[Farmacologia] Domanda 535: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0536",
    q: "[Farmacologia] Domanda 536: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0537",
    q: "[Farmacologia] Domanda 537: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0538",
    q: "[Farmacologia] Domanda 538: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0539",
    q: "[Farmacologia] Domanda 539: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0540",
    q: "[Farmacologia] Domanda 540: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0541",
    q: "[Farmacologia] Domanda 541: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0542",
    q: "[Farmacologia] Domanda 542: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0543",
    q: "[Farmacologia] Domanda 543: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0544",
    q: "[Farmacologia] Domanda 544: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0545",
    q: "[Farmacologia] Domanda 545: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0546",
    q: "[Farmacologia] Domanda 546: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0547",
    q: "[Farmacologia] Domanda 547: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0548",
    q: "[Farmacologia] Domanda 548: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0549",
    q: "[Farmacologia] Domanda 549: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0550",
    q: "[Farmacologia] Domanda 550: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0551",
    q: "[Farmacologia] Domanda 551: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0552",
    q: "[Farmacologia] Domanda 552: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0553",
    q: "[Farmacologia] Domanda 553: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0554",
    q: "[Farmacologia] Domanda 554: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0555",
    q: "[Farmacologia] Domanda 555: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0556",
    q: "[Farmacologia] Domanda 556: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0557",
    q: "[Farmacologia] Domanda 557: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0558",
    q: "[Farmacologia] Domanda 558: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0559",
    q: "[Farmacologia] Domanda 559: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0560",
    q: "[Farmacologia] Domanda 560: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0561",
    q: "[Farmacologia] Domanda 561: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0562",
    q: "[Farmacologia] Domanda 562: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0563",
    q: "[Farmacologia] Domanda 563: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0564",
    q: "[Farmacologia] Domanda 564: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0565",
    q: "[Farmacologia] Domanda 565: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0566",
    q: "[Farmacologia] Domanda 566: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0567",
    q: "[Farmacologia] Domanda 567: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0568",
    q: "[Farmacologia] Domanda 568: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0569",
    q: "[Farmacologia] Domanda 569: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0570",
    q: "[Farmacologia] Domanda 570: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0571",
    q: "[Farmacologia] Domanda 571: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0572",
    q: "[Farmacologia] Domanda 572: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0573",
    q: "[Farmacologia] Domanda 573: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0574",
    q: "[Farmacologia] Domanda 574: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0575",
    q: "[Farmacologia] Domanda 575: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0576",
    q: "[Farmacologia] Domanda 576: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0577",
    q: "[Farmacologia] Domanda 577: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0578",
    q: "[Farmacologia] Domanda 578: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0579",
    q: "[Farmacologia] Domanda 579: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0580",
    q: "[Farmacologia] Domanda 580: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0581",
    q: "[Farmacologia] Domanda 581: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0582",
    q: "[Farmacologia] Domanda 582: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0583",
    q: "[Farmacologia] Domanda 583: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0584",
    q: "[Farmacologia] Domanda 584: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0585",
    q: "[Farmacologia] Domanda 585: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0586",
    q: "[Farmacologia] Domanda 586: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0587",
    q: "[Farmacologia] Domanda 587: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0588",
    q: "[Farmacologia] Domanda 588: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0589",
    q: "[Farmacologia] Domanda 589: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0590",
    q: "[Farmacologia] Domanda 590: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0591",
    q: "[Farmacologia] Domanda 591: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0592",
    q: "[Farmacologia] Domanda 592: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0593",
    q: "[Farmacologia] Domanda 593: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0594",
    q: "[Farmacologia] Domanda 594: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0595",
    q: "[Farmacologia] Domanda 595: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0596",
    q: "[Farmacologia] Domanda 596: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0597",
    q: "[Farmacologia] Domanda 597: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0598",
    q: "[Farmacologia] Domanda 598: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0599",
    q: "[Farmacologia] Domanda 599: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0600",
    q: "[Farmacologia] Domanda 600: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0601",
    q: "[Farmacologia] Domanda 601: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0602",
    q: "[Farmacologia] Domanda 602: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0603",
    q: "[Farmacologia] Domanda 603: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0604",
    q: "[Farmacologia] Domanda 604: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0605",
    q: "[Farmacologia] Domanda 605: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0606",
    q: "[Farmacologia] Domanda 606: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0607",
    q: "[Farmacologia] Domanda 607: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0608",
    q: "[Farmacologia] Domanda 608: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0609",
    q: "[Farmacologia] Domanda 609: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0610",
    q: "[Farmacologia] Domanda 610: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0611",
    q: "[Farmacologia] Domanda 611: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0612",
    q: "[Farmacologia] Domanda 612: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0613",
    q: "[Farmacologia] Domanda 613: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0614",
    q: "[Farmacologia] Domanda 614: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0615",
    q: "[Farmacologia] Domanda 615: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0616",
    q: "[Farmacologia] Domanda 616: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0617",
    q: "[Farmacologia] Domanda 617: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0618",
    q: "[Farmacologia] Domanda 618: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0619",
    q: "[Farmacologia] Domanda 619: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0620",
    q: "[Farmacologia] Domanda 620: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0621",
    q: "[Farmacologia] Domanda 621: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0622",
    q: "[Farmacologia] Domanda 622: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0623",
    q: "[Farmacologia] Domanda 623: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0624",
    q: "[Farmacologia] Domanda 624: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0625",
    q: "[Farmacologia] Domanda 625: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0626",
    q: "[Farmacologia] Domanda 626: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0627",
    q: "[Farmacologia] Domanda 627: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0628",
    q: "[Farmacologia] Domanda 628: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0629",
    q: "[Farmacologia] Domanda 629: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0630",
    q: "[Farmacologia] Domanda 630: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0631",
    q: "[Farmacologia] Domanda 631: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0632",
    q: "[Farmacologia] Domanda 632: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0633",
    q: "[Farmacologia] Domanda 633: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0634",
    q: "[Farmacologia] Domanda 634: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0635",
    q: "[Farmacologia] Domanda 635: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0636",
    q: "[Farmacologia] Domanda 636: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0637",
    q: "[Farmacologia] Domanda 637: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0638",
    q: "[Farmacologia] Domanda 638: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0639",
    q: "[Farmacologia] Domanda 639: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0640",
    q: "[Farmacologia] Domanda 640: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0641",
    q: "[Farmacologia] Domanda 641: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0642",
    q: "[Farmacologia] Domanda 642: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0643",
    q: "[Farmacologia] Domanda 643: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0644",
    q: "[Farmacologia] Domanda 644: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0645",
    q: "[Farmacologia] Domanda 645: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0646",
    q: "[Farmacologia] Domanda 646: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0647",
    q: "[Farmacologia] Domanda 647: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0648",
    q: "[Farmacologia] Domanda 648: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0649",
    q: "[Farmacologia] Domanda 649: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_ph_0650",
    q: "[Farmacologia] Domanda 650: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "farmacologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
];
