import type { QuizQuestion } from "./quizBank";

// Banca domande dedicata a SIMULAZIONE CONCORSO
// Separata da QUIZ_BANK (Daily/Weekly) per evitare ripetizioni e consentire aggiornamenti mirati.

export const QUIZ_BANK_CONCORSO: QuizQuestion[] = [
  {
    id: "qc2001",
    q: "DM 739/1994: quale elemento definisce il profilo professionale dell'infermiere?",
    options: [
      "Mansioni delegate dal medico",
      "Responsabilità e funzioni proprie della professione",
      "Solo atti tecnici",
      "Regole contrattuali",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Definisce campo proprio, responsabilità e funzioni dell'infermiere (profilo).",
  },
  {
    id: "qc2002",
    q: "Legge 42/1999: quale concetto supera definitivamente il 'mansionario'?",
    options: [
      "Infermiere come ausiliario",
      "Infermiere come professione sanitaria con campo proprio",
      "Infermiere come tecnico esecutore",
      "Infermiere senza autonomia",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "La 42/1999 abolisce il mansionario e definisce la professione sanitaria con campo proprio.",
  },
  {
    id: "qc2003",
    q: "Legge 251/2000: quale sviluppo introduce per le professioni infermieristiche?",
    options: [
      "Solo formazione di base",
      "Autonomia, dirigenza e sviluppo delle funzioni",
      "Riduzione competenze",
      "Abolizione responsabilità",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Rafforza autonomia e prevede ruoli di coordinamento/dirigenza e sviluppo professionale.",
  },
  {
    id: "qc2004",
    q: "Consenso informato (L. 219/2017): chi decide sui trattamenti se il paziente è capace?",
    options: [
      "Solo il medico",
      "La struttura",
      "La persona interessata (paziente)",
      "Il familiare sempre",
    ],
    answer: 2,
    category: "norme",
    difficulty: "easy",
    explain: "Tutela autodeterminazione: decide il paziente capace; altrimenti rappresentanti secondo legge.",
  },
  {
    id: "qc2005",
    q: "Documentazione infermieristica: perché è rilevante anche legalmente?",
    options: [
      "Serve solo per statistiche",
      "È documento sanitario con valore probatorio",
      "È facoltativa",
      "Sostituisce il consenso",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "È tracciabilità dell'assistenza e ha rilevanza medico-legale.",
  },
  {
    id: "qc2006",
    q: "Segreto professionale: quando può essere derogato legittimamente?",
    options: [
      "Mai",
      "Sempre su richiesta del collega",
      "Nei casi previsti da legge/autorità o giusta causa",
      "Quando conviene",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La comunicazione di dati è ammessa nei limiti di legge o per obblighi/giusta causa, rispettando privacy.",
  },
  {
    id: "qc2007",
    q: "GDPR: qual è un principio chiave nel trattamento dei dati sanitari?",
    options: [
      "Conservare tutto per sempre",
      "Minimizzazione e finalità determinate",
      "Condividere senza limiti",
      "Nessun controllo accessi",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Dati adeguati e limitati; finalità determinate; sicurezza e controllo accessi.",
  },
  {
    id: "qc2008",
    q: "Legge 24/2017 (Gelli-Bianco): cosa promuove per la sicurezza delle cure?",
    options: [
      "Segretezza degli errori",
      "Gestione rischio clinico e buone pratiche",
      "Riduzione segnalazioni",
      "Nessuna formazione",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Rafforza sicurezza delle cure, risk management e buone pratiche/linee guida.",
  },
  {
    id: "qc2009",
    q: "Responsabilità professionale: quali elementi sono tipici per configurare colpa?",
    options: [
      "Solo evento avverso",
      "Condotta colposa + nesso causale + danno",
      "Solo intenzionalità",
      "Solo presenza linee guida",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Elementi tipici: colpa, nesso causale, danno (oltre a violazione regole di condotta).",
  },
  {
    id: "qc2010",
    q: "Delega: cosa NON è delegabile?",
    options: [
      "Attività alberghiere",
      "Attività che richiede giudizio clinico infermieristico",
      "Rilevazione parametri",
      "Trasporto campioni",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Il giudizio/decisione assistenziale resta in capo al professionista; alcune attività possono essere attribuite secondo regole.",
  },
  {
    id: "qc2011",
    q: "OPI: funzione principale dell'Ordine delle Professioni Infermieristiche?",
    options: [
      "Gestire turni",
      "Tutela della professione e garanzia per il cittadino",
      "Stabilire terapie",
      "Sostituire il sindacato",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "L'Ordine tutela la professione e garantisce qualità/etica a tutela dei cittadini.",
  },
  {
    id: "qc2012",
    q: "Codice Deontologico: a cosa serve?",
    options: [
      "Manuale farmaci",
      "Principi e doveri etico-professionali",
      "Sostituisce le leggi",
      "È opzionale",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Indica principi e doveri; si integra con leggi e regolamenti.",
  },
  {
    id: "qc2013",
    q: "Rifiuto di trattamento: se il paziente capace rifiuta, l'infermiere deve:",
    options: [
      "Ignorare e procedere",
      "Rispettare e documentare, informando l'équipe secondo procedure",
      "Chiamare la polizia",
      "Dimettere il paziente",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Va rispettata autodeterminazione; documentare e comunicare al team.",
  },
  {
    id: "qc2014",
    q: "DAT: cosa sono?",
    options: [
      "Prescrizione medica",
      "Volontà espresse in previsione di futura incapacità",
      "Consenso generico",
      "Modulo farmaci",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Strumento L.219/2017: volontà per future condizioni di incapacità.",
  },
  {
    id: "qc2015",
    q: "Rischio clinico: cos'è un 'near miss'?",
    options: [
      "Evento senza conseguenze ma che avrebbe potuto causare danno",
      "Evento sempre mortale",
      "Errore intenzionale",
      "Guasto elettrico",
    ],
    answer: 0,
    category: "norme",
    difficulty: "medium",
    explain: "Near miss = mancato evento avverso: occasione di apprendimento.",
  },
  {
    id: "qc2016",
    q: "Incident reporting: scopo principale?",
    options: [
      "Punire",
      "Migliorare il sistema prevenendo recidive",
      "Ridurre costi subito",
      "Attribuire colpe",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Approccio sistemico: imparare dagli eventi per prevenire.",
  },
  {
    id: "qc2017",
    q: "D.Lgs 81/2008: obbligo del lavoratore?",
    options: [
      "Ignorare DPI",
      "Usare correttamente DPI e seguire procedure di sicurezza",
      "Decidere norme",
      "Non segnalare rischi",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Il lavoratore deve prendersi cura della propria sicurezza e usare DPI/seguire procedure.",
  },
  {
    id: "qc2018",
    q: "Contenzione: principio generale?",
    options: [
      "Sempre appropriata",
      "Ultima ratio, proporzionata e documentata secondo protocollo",
      "Mai documentata",
      "Solo su richiesta famiglia",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Va limitata, motivata, monitorata e documentata secondo norme/protocolli.",
  },
  {
    id: "qc2019",
    q: "Regola '5G/7G': serve a:",
    options: [
      "Aumentare velocità",
      "Ridurre errori in terapia",
      "Sostituire doppio controllo",
      "Eliminare documentazione",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Giusto paziente/farmaco/dose/via/orario (+ altri) riducono errori.",
  },
  {
    id: "qc2020",
    q: "Farmaci ad alto rischio: cosa aumenta sicurezza?",
    options: [
      "Stoccaggio casuale",
      "Doppio controllo e standardizzazione",
      "Uso abbreviazioni",
      "Preparazioni non etichettate",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Standard, etichette, doppio controllo e protocolli riducono eventi gravi.",
  },
  {
    id: "qc2021",
    q: "Privacy: quando è lecito discutere informazioni cliniche in corridoio?",
    options: [
      "Sempre",
      "Solo in spazi idonei e con necessità di cura",
      "Se a voce bassa",
      "Se con un collega qualsiasi",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Le informazioni vanno condivise solo con chi è coinvolto e in ambienti appropriati.",
  },
  {
    id: "qc2022",
    q: "Cartella infermieristica: quale caratteristica è essenziale?",
    options: [
      "Annullabile con bianchetto",
      "Tracciabile, cronologica, completa e tempestiva",
      "Solo a fine turno",
      "Solo se richiesto",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Deve garantire tracciabilità e tempestività: niente cancellazioni non tracciate.",
  },
  {
    id: "qc2023",
    q: "Errore terapeutico: prima cosa dopo averlo identificato?",
    options: [
      "Nasconderlo",
      "Mettere in sicurezza il paziente e avvisare secondo protocollo",
      "Aspettare il medico",
      "Scrivere dopo giorni",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Priorità: sicurezza paziente, poi comunicazione e segnalazione.",
  },
  {
    id: "qc2024",
    q: "Deleghe OSS: criterio guida l'attribuzione?",
    options: [
      "Comodità",
      "Competenza/formazione e protocolli, con supervisione appropriata",
      "Solo anzianità",
      "Richiesta del paziente",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Attribuzione basata su competenze e contesto, con supervisione.",
  },
  {
    id: "qc2025",
    q: "Somministrazione EV: cosa documenti sempre?",
    options: [
      "Solo il farmaco",
      "Farmaco, dose, via, orario, effetti/rilevazioni pertinenti",
      "Solo l'orario",
      "Solo la firma",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Documentazione completa e tracciabile migliora continuità e sicurezza.",
  },
  {
    id: "qc2026",
    q: "Caduta del paziente: prevenzione include?",
    options: [
      "Alzare sponde sempre",
      "Valutazione rischio, ambiente sicuro, informazione e ausili",
      "Solo videosorveglianza",
      "Solo restrizioni",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Approccio multifattoriale: valutazione e interventi personalizzati.",
  },
  {
    id: "qc2027",
    q: "Lesioni da pressione: misura 'best practice'?",
    options: [
      "Cambio postura e valutazione cute programmati",
      "Solo crema",
      "Solo sponde",
      "Solo massaggio su prominenze",
    ],
    answer: 0,
    category: "norme",
    difficulty: "medium",
    explain: "Riposizionamento, superfici antidecubito e valutazione rischio sono base.",
  },
  {
    id: "qc2028",
    q: "Consenso: chi può firmare per paziente incapace?",
    options: [
      "Chiunque",
      "Rappresentante legale/amministratore di sostegno/tutore secondo legge",
      "Un collega",
      "Il vicino",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Serve titolo legale o strumenti previsti (ADS, tutore, ecc.).",
  },
  {
    id: "qc2029",
    q: "Comunicazione con familiari: cosa è corretto?",
    options: [
      "Dare dettagli a chiunque chiami",
      "Verificare identità/autorizzazioni e limitare info al necessario",
      "Inviare foto su WhatsApp",
      "Dire tutto in sala d'attesa",
    ],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Protezione dati: verificare autorizzazione e necessità.",
  },
  {
    id: "qc2030",
    q: "Rifiuto di cure: cosa è fondamentale registrare?",
    options: [
      "Solo la firma",
      "Informazioni fornite, decisione del paziente, eventuali testimoni/procedure",
      "Solo diagnosi",
      "Solo terapia proposta",
    ],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Documentare comunicazione e decisione è essenziale.",
  },
  {
    id: "qc2062",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (31)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2063",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (32)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2064",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (33)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2065",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (34)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2066",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (35)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2067",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (36)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2068",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (37)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2069",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (38)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2070",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (39)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2071",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (40)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2072",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (41)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2073",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (42)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2074",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (43)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2075",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (44)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2076",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (45)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2077",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (46)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2078",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (47)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2079",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (48)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2080",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (49)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2081",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (50)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2082",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (51)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2083",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (52)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2084",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (53)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2085",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (54)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2086",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (55)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2087",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (56)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2088",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (57)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2089",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (58)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2090",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (59)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2091",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (60)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2092",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (61)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2093",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (62)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2094",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (63)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2095",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (64)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2096",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (65)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2097",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (66)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2098",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (67)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2099",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (68)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2100",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (69)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2101",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (70)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2102",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (71)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2103",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (72)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2104",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (73)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2105",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (74)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2106",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (75)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2107",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (76)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2108",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (77)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2109",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (78)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2110",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (79)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2111",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (80)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2112",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (81)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2113",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (82)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2114",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (83)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2115",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (84)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2116",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (85)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2117",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (86)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2118",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (87)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2119",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (88)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2120",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (89)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2121",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (90)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2122",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (91)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2123",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (92)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2124",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (93)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2125",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (94)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2126",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (95)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2127",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (96)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2128",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (97)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2129",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (98)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2130",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (99)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2131",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (100)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2132",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (101)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2133",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (102)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2134",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (103)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2135",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (104)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2136",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (105)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2137",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (106)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2138",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (107)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2139",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (108)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2140",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (109)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2141",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (110)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2142",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (111)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2143",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (112)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2144",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (113)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2145",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (114)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2146",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (115)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2147",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (116)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2148",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (117)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2149",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (118)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2150",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (119)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2151",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (120)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2152",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (121)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2153",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (122)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2154",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (123)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2155",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (124)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2156",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (125)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2157",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (126)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2158",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (127)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2159",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (128)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2160",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (129)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2161",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (130)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2162",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (131)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2163",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (132)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2164",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (133)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2165",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (134)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2166",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (135)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2167",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (136)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2168",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (137)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2169",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (138)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2170",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (139)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
  {
    id: "qc2171",
    q: "In un concorso, quale affermazione è più corretta riguardo alla tracciabilità delle correzioni in cartella? (140)",
    options: [
      "Si può usare il bianchetto",
      "Si cancella e si riscrive senza nota",
      "Le modifiche devono essere tracciabili secondo procedure (data/ora/firma)",
      "Non è rilevante",
    ],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "La tracciabilità delle modifiche (data/ora/firma e procedure) è essenziale per integrità del documento sanitario.",
  },
];
