import type { QuizQuestion } from "@/features/cards/quiz/quizBank";

// University-focused question bank (theory-heavy, less clinical).
export const QUIZ_BANK_UNIVERSITY: QuizQuestion[] = [
  {
    id: "FARMA_001",
    category: "farmacologia",
    q: "Quale parametro descrive meglio l'estensione di distribuzione di un farmaco nei tessuti rispetto al plasma?",
    options: [
      "Clearance (CL)",
      "Volume di distribuzione (Vd)",
      "Emivita (t½)",
      "Biodisponibilità (F)",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_002",
    category: "farmacologia",
    q: "Un aumento della clearance (CL), a parità di dose e biodisponibilità, tende a:",
    options: [
      "Aumentare AUC",
      "Ridurre AUC",
      "Non modificare AUC",
      "Aumentare Cmax sempre",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_003",
    category: "farmacologia",
    q: "Il tempo per raggiungere lo steady state con cinetica di primo ordine dipende soprattutto da:",
    options: [
      "Dose somministrata",
      "Intervallo di somministrazione",
      "Emivita",
      "Vd",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_004",
    category: "farmacologia",
    q: "Un agonista parziale rispetto a un agonista pieno ha:",
    options: [
      "Efficacia massima maggiore",
      "Efficacia massima minore",
      "Potenza sempre minore",
      "Affinità nulla",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_005",
    category: "farmacologia",
    q: "Un antagonista competitivo tipicamente:",
    options: [
      "Riduce Emax",
      "Sposta la curva a destra senza ridurre Emax",
      "Sposta la curva a sinistra",
      "Aumenta Emax",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_006",
    category: "farmacologia",
    q: "Quale affermazione su biodisponibilità (F) è corretta?",
    options: [
      "È sempre 100% per via orale",
      "È influenzata dal primo passaggio epatico",
      "Coincide con Vd",
      "È uguale alla clearance",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_007",
    category: "farmacologia",
    q: "Con cinetica di ordine zero (saturazione), l'eliminazione:",
    options: [
      "È proporzionale alla concentrazione",
      "Avviene a velocità costante",
      "Non dipende dal fegato",
      "Non può avvenire nei farmaci",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_008",
    category: "farmacologia",
    q: "La relazione AUC = Dose/CL è valida principalmente per:",
    options: [
      "Somministrazione endovenosa con cinetica lineare",
      "Solo via orale",
      "Solo per farmaci lipofili",
      "Solo per antagonisti competitivi",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_009",
    category: "farmacologia",
    q: "Un farmaco altamente legato alle proteine plasmatiche tende ad avere:",
    options: [
      "Frazione libera maggiore",
      "Frazione libera minore",
      "Clearance renale sempre maggiore",
      "Biodisponibilità aumentata",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_010",
    category: "farmacologia",
    q: "Che cos'è l'EC50?",
    options: [
      "Dose che dà 50% della risposta massima",
      "Concentrazione che dà 50% dell'effetto massimo",
      "Clearance al 50%",
      "Vd al 50%",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_011",
    category: "farmacologia",
    q: "L'indice terapeutico (TI) è più alto quando:",
    options: [
      "La distanza tra dose efficace e tossica è ampia",
      "La distanza è minima",
      "Il farmaco è lipofilo",
      "La clearance è bassa",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_012",
    category: "farmacologia",
    q: "Un induttore enzimatico (es. CYP) tende a:",
    options: [
      "Aumentare concentrazioni plasmatiche del substrato",
      "Ridurre concentrazioni plasmatiche del substrato",
      "Non modificare AUC",
      "Ridurre metabolismo",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_013",
    category: "farmacologia",
    q: "Quale meccanismo spiega la tachifilassi?",
    options: [
      "Aumento recettori",
      "Desensibilizzazione/down-regulation recettoriale",
      "Aumento biodisponibilità",
      "Riduzione clearance",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_014",
    category: "farmacologia",
    q: "La clearance totale di un farmaco è:",
    options: [
      "Somma delle clearance d'organo (es. renale+epatica)",
      "Uguale sempre alla Vd",
      "Inversamente proporzionale alla dose",
      "Uguale sempre all'emivita",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FARMA_015",
    category: "farmacologia",
    q: "In genere, aumentando Vd a parità di CL, l'emivita:",
    options: [
      "Diminuisce",
      "Aumenta",
      "Resta invariata",
      "Diventa zero",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_001",
    category: "anatomia",
    q: "Quale struttura attraversa il forame ovale (base cranica)?",
    options: [
      "Nervo ottico",
      "Nervo mandibolare (V3)",
      "Nervo faciale",
      "Arteria carotide interna",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_002",
    category: "anatomia",
    q: "Il dotto toracico drena principalmente:",
    options: [
      "Solo il quadrante superiore destro",
      "Tutta la linfa eccetto quadrante superiore destro",
      "Solo gli arti superiori",
      "Solo l'addome",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_003",
    category: "anatomia",
    q: "Quale valvola cardiaca si trova tra atrio sinistro e ventricolo sinistro?",
    options: [
      "Tricuspide",
      "Mitralica",
      "Aortica",
      "Polmonare",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_004",
    category: "anatomia",
    q: "Il nervo frenico origina principalmente da:",
    options: [
      "C1-C2",
      "C3-C5",
      "T1-T4",
      "L4-L5",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_005",
    category: "anatomia",
    q: "L'arteria coronaria destra irrora spesso:",
    options: [
      "Nodo seno-atriale e nodo AV (variabile)",
      "Solo ventricolo sinistro",
      "Solo atrio sinistro",
      "Solo setto interventricolare anteriore",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_006",
    category: "anatomia",
    q: "Il plesso brachiale è formato dalle radici:",
    options: [
      "C1-C4",
      "C5-T1",
      "T1-T12",
      "L1-S1",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_007",
    category: "anatomia",
    q: "Quale osso fa parte della volta cranica?",
    options: [
      "Sfenoide",
      "Frontale",
      "Vomer",
      "Etmoide (lamina perpendicolare)",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_008",
    category: "anatomia",
    q: "La vena porta epatica riceve sangue da:",
    options: [
      "Solo fegato",
      "Intestino e milza (sistema splancnico)",
      "Solo reni",
      "Solo polmoni",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_009",
    category: "anatomia",
    q: "Il muscolo principale dell'inspirazione tranquilla è:",
    options: [
      "Intercostali interni",
      "Diaframma",
      "Grande pettorale",
      "Retto addominale",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_010",
    category: "anatomia",
    q: "Quale nervo è responsabile dell'abduzione del braccio oltre i 15°?",
    options: [
      "Nervo ascellare",
      "Nervo sovrascapolare",
      "Nervo radiale",
      "Nervo ulnare",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_011",
    category: "anatomia",
    q: "Il legamento crociato anteriore limita principalmente:",
    options: [
      "Traslazione posteriore tibia",
      "Traslazione anteriore tibia",
      "Varismo",
      "Rotazione esterna",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_012",
    category: "anatomia",
    q: "Il colon ascendente è principalmente:",
    options: [
      "Intraperitoneale",
      "Retroperitoneale secondario",
      "Nello scavo pelvico",
      "Nel mediastino",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_013",
    category: "anatomia",
    q: "Quale struttura contiene il liquido cefalorachidiano?",
    options: [
      "Dura madre",
      "Spazio subaracnoideo",
      "Spazio epidurale",
      "Seno sagittale",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_014",
    category: "anatomia",
    q: "Il nervo vago (X) è un nervo:",
    options: [
      "Solo sensitivo",
      "Solo motorio",
      "Misto con parasimpatico",
      "Solo simpatico",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "ANAT_015",
    category: "anatomia",
    q: "L'arteria femorale diventa arteria poplitea passando attraverso:",
    options: [
      "Canale del carpo",
      "Iato dell'adduttore",
      "Fossa cubitale",
      "Forame otturatorio",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_001",
    category: "fisiologia",
    q: "La gittata cardiaca (CO) è data da:",
    options: [
      "FC × volume sistolico",
      "PA × resistenze",
      "Vd × CL",
      "FEV1 × CVF",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_002",
    category: "fisiologia",
    q: "Quale ormone aumenta la glicemia stimolando gluconeogenesi?",
    options: [
      "Insulina",
      "Glucagone",
      "Calcitonina",
      "Ossitocina",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_003",
    category: "fisiologia",
    q: "Il potenziale di equilibrio del K+ è vicino a:",
    options: [
      "+60 mV",
      "0 mV",
      "-90 mV",
      "+120 mV",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_004",
    category: "fisiologia",
    q: "Nel rene, la maggior parte del sodio viene riassorbita in:",
    options: [
      "Dotto collettore",
      "Tubulo prossimale",
      "Ansa ascendente sottile",
      "Capsula di Bowman",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_005",
    category: "fisiologia",
    q: "L'ADH aumenta principalmente:",
    options: [
      "Filtrazione glomerulare",
      "Riassorbimento di acqua nel dotto collettore",
      "Secrezione di bicarbonato",
      "Escrezione di Na+",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_006",
    category: "fisiologia",
    q: "La curva di dissociazione Hb-O2 si sposta a destra con:",
    options: [
      "Alcalosi",
      "Ipotermia",
      "Aumento CO2 / acidosi",
      "Riduzione 2,3-BPG",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_007",
    category: "fisiologia",
    q: "La ventilazione alveolare aumenta quando:",
    options: [
      "Diminuisce frequenza respiratoria a parità di volume",
      "Aumenta volume corrente riducendo lo spazio morto relativo",
      "Aumenta solo spazio morto",
      "Diminuisce volume corrente",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_008",
    category: "fisiologia",
    q: "Quale recettore è accoppiato a proteina Gs aumentando cAMP?",
    options: [
      "β1-adrenergico",
      "α1-adrenergico",
      "M3 muscarinico",
      "Gi accoppiato",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_009",
    category: "fisiologia",
    q: "Nel ciclo cellulare, la fase di sintesi del DNA è:",
    options: [
      "G0",
      "G1",
      "S",
      "M",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_010",
    category: "fisiologia",
    q: "Il pH ematico normale è circa:",
    options: [
      "6.8",
      "7.0",
      "7.4",
      "7.8",
    ],
    answer: 2,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_011",
    category: "fisiologia",
    q: "Quale trasporto è tipico del glucosio nel tubulo prossimale?",
    options: [
      "Diffusione semplice",
      "Simporto Na+/glucosio (SGLT)",
      "Antiporto K+/H+",
      "Canali Cl-",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_012",
    category: "fisiologia",
    q: "L'equazione di Nernst descrive:",
    options: [
      "Relazione tra pH e CO2",
      "Potenziale di equilibrio di uno ione",
      "Legge di Poiseuille",
      "Legge di Dalton",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_013",
    category: "fisiologia",
    q: "La pressione arteriosa media (MAP) è approssimativamente:",
    options: [
      "PAS + PAD",
      "(PAS + 2×PAD)/3",
      "(2×PAS + PAD)/3",
      "PAD - PAS",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_014",
    category: "fisiologia",
    q: "Il surfattante polmonare riduce:",
    options: [
      "Compliance polmonare",
      "Tensione superficiale alveolare",
      "Ventilazione",
      "Perfusione",
    ],
    answer: 1,
    difficulty: "medium",
    explain: "",
  },
  {
    id: "FISIO_015",
    category: "fisiologia",
    q: "La depolarizzazione rapida del miocardio ventricolare (fase 0) è dovuta a:",
    options: [
      "Ingresso Na+ rapido",
      "Uscita K+",
      "Ingresso Ca2+ L-type",
      "Pompa Na/K",
    ],
    answer: 0,
    difficulty: "medium",
    explain: "",
  },
];
