import type { QuizQuestion } from "./quizBank";

// ✅ Banca domande CONCORSO (separata)
// - pensata per la modalità "Simulazione Concorso"
// - NON usata da Daily/Weekly
// - 30 domande (da prove scritte concorso) (prevalenza norme/deontologia + mix clinico/procedure)
export const QUIZ_BANK_CONCORSO: QuizQuestion[] = [
  {
    id: "qc0001",
    q: "Il consenso informato deve essere esplicitamente richiesto in forma scritta:",
    options: ["Per la trasfusione di sangue, ma non per la donazione di sangue", "Sia per la trasfusione di sangue, sia per la donazione di sangue", "Per il posizionamento di cateteri vescicali", "Per la somministrazione di farmaci in ambito ospedaliero"],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Nel quesito concorsuale, il consenso scritto è richiesto per l’emotrasfusione e (in questo test) anche per la donazione.",
  },
  {
    id: "qc0002",
    q: "Il segreto professionale a cui sono vincolati gli esercenti le professioni sanitarie concerne:",
    options: ["Solo le notizie di carattere sanitario", "Ogni segreto/notizia relativo al paziente", "Ogni genere di notizia escluse quelle di carattere sanitario", "Le notizie relative alla corrispondenza del paziente"],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Il segreto professionale tutela l’intera sfera informativa della persona assistita, non solo i dati clinici.",
  },
  {
    id: "qc0003",
    q: "Se a seguito di un'azione assistenziale, una figura di supporto inesperta provoca, involontariamente, un danno ad un paziente l'infermiere risponderà per:",
    options: ["Colpa in vigilando", "Reato di pericolo", "Colpa in eligendo", "Tutte le precedenti alternative sono corrette"],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "Se la figura di supporto opera sotto supervisione, il profilo richiamato è la responsabilità per mancata vigilanza (culpa in vigilando).",
  },
  {
    id: "qc0004",
    q: "Tra i criteri generali della terapia del dolore risulta importante somministrare i farmaci:",
    options: ["Prima che compaia il dolore", "Quando compare il dolore", "Al bisogno", "Solo quando il dolore è insopportabile"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Principio: prevenire e controllare il dolore, evitando di “inseguire” il sintomo quando è già intenso.",
  },
  {
    id: "qc0005",
    q: "Lo studio Caso Controllo si utilizza per:",
    options: ["Calcolare l'incidenza della malattia considerata", "Calcolare la prevalenza della malattia considerata", "Stimare il rischio relativo riferito ad uno o più sospetti fattori di rischio", "Valutare l'andamento nel tempo delle malattie"],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "Nel caso-controllo si confronta l’esposizione tra casi e controlli per stimare l’associazione con fattori di rischio.",
  },
  {
    id: "qc0006",
    q: "Il Codice Deontologico dell'Infermiere è stato emanato:",
    options: ["Dalla Federazione Nazionale dei Collegi IPASVI", "Con Decreto dal Ministero della Salute", "Con Decreto Legislativo dal Governo", "Nel Piano Sanitario Nazionale 1998–2000"],
    answer: 1,
    category: "norme",
    difficulty: "easy",
    explain: "Il Codice è emanato dall’ente professionale (FNOPI, ex IPASVI).",
  },
  {
    id: "qc0007",
    q: "La capacità di uno strumento di misurare il vero fenomeno oggetto di misurazione è definita:",
    options: ["Validità", "Affidabilità", "Precisione", "Sensibilità"],
    answer: 0,
    category: "norme",
    difficulty: "easy",
    explain: "Validità = misura ciò che deve misurare. Affidabilità = ripetibilità/consistenza della misura.",
  },
  {
    id: "qc0008",
    q: "Uno studio di follow-up si effettua:",
    options: ["Per diagnosi precoce di malattia", "Per valutare, nel tempo, i risultati di una procedura terapeutica", "Prima di effettuare una terapia o una procedura diagnostica", "Solo su pazienti terminali"],
    answer: 3,
    category: "norme",
    difficulty: "easy",
    explain: "Follow-up = osservazione nel tempo degli esiti dopo un intervento/terapia.",
  },
  {
    id: "qc0009",
    q: "Il lavaggio delle mani, come precauzione standard, mira specificamente a prevenire:",
    options: ["La trasmissione di tutti gli agenti virali", "La trasmissione di agenti virali presenti nel sangue ed altri liquidi biologici", "Le infezioni ospedaliere", "Le infezioni respiratorie"],
    answer: 2,
    category: "procedure",
    difficulty: "easy",
    explain: "È la misura chiave per ridurre le infezioni correlate all’assistenza (ICA).",
  },
  {
    id: "qc0010",
    q: "Lo scopo della prevenzione secondaria è:",
    options: ["La diagnosi precoce", "L’educazione sanitaria", "La riabilitazione", "La bonifica ambientale"],
    answer: 0,
    category: "norme",
    difficulty: "easy",
    explain: "Secondaria = diagnosi precoce/screening.",
  },
  {
    id: "qc0011",
    q: "I trattamenti sanitari sono:",
    options: ["Sempre obbligatori", "Facoltativi per i maggiorenni ma obbligatori per i minorenni", "Obbligatori solo se disposti per legge", "Sempre facoltativi"],
    answer: 2,
    category: "norme",
    difficulty: "medium",
    explain: "Regola: consenso libero e informato; obbligo solo nei casi previsti dalla legge.",
  },
  {
    id: "qc0012",
    q: "Quali sono i principi su cui si base il SSN, formulati nell'articolo 1 della Legge 833 del 1978 e richiamati nell'articolo 1 del DLgs 229/99?",
    options: ["Sistema dell’accreditamento e dell’erogazione diretta, sperimentazioni gestionali, modulo convenzionale e assistenza indiretta", "Uguaglianza, universalità, globalità e volontarietà", "Libertà di scelta, qualità, integrazione socio-sanitaria e continuità assistenziale", "Nessuna delle precedenti alternative è corretta"],
    answer: 2,
    category: "norme",
    difficulty: "hard",
    explain: "Nel quesito, i principi del SSN sono indicati come: uguaglianza, universalità, globalità e volontarietà.",
  },
  {
    id: "qc0013",
    q: "I farmaci campione possono essere detenuti soltanto:",
    options: ["Dall’infermiere come tutti gli altri farmaci ma non sono somministrabili", "Dal medico e sono somministrabili dall’infermiere", "Dal medico ma non sono somministrabili dall’infermiere", "Dall’infermiere con gli altri farmaci, purché debitamente contrassegnati"],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "Nel test, i campioni sono detenuti dal medico; l’infermiere può somministrare su prescrizione.",
  },
  {
    id: "qc0014",
    q: "L’infermiere, nel compilare la cartella clinica integrata, risponde di falso ideologico quando:",
    options: ["Attesta falsamente che un fatto è stato da lui compiuto o è avvenuto in sua presenza oppure omette o altera dichiarazioni da lui ricevute", "Esegue una contraffazione del documento, cancellando, sostituendo o aggiungendo dei dati", "Si rifiuta di compilare la cartella clinica integrata per motivi ideologici", "Tutte le precedenti alternative sono corrette"],
    answer: 0,
    category: "norme",
    difficulty: "hard",
    explain: "Falso ideologico = attestare il falso in un documento formalmente vero (diverso dal falso materiale/contraffazione).",
  },
  {
    id: "qc0015",
    q: "Secondo quanto espresso dal Codice Deontologico dell’Infermiere, non viene riportato come attività propria dell’Infermiere:",
    options: ["La promozione, attraverso l’educazione, di stili di vita sani e di una cultura della salute", "La tutela della riservatezza delle informazioni relative alla persona assistita", "La continuità assistenziale", "Il ricorso, per alleviare i sintomi, in particolare quelle prevedibili, all’uso di placebo"],
    answer: 0,
    category: "norme",
    difficulty: "hard",
    explain: "L’uso di placebo non è indicato come attività propria e pone criticità etiche/di trasparenza.",
  },
  {
    id: "qc0016",
    q: "Per determinanti in epidemiologia si intendono quei fattori:",
    options: ["La cui alterazione induce un cambiamento nella frequenza o nei caratteri di una malattia", "Che permettono di individuare la causa di una malattia", "Che determinano la malattia", "Che determinano la tipologia delle complicanze di una malattia"],
    answer: 0,
    category: "norme",
    difficulty: "medium",
    explain: "Determinanti = fattori che influenzano frequenza e caratteristiche di un evento di salute.",
  },
  {
    id: "qc0017",
    q: "Il Patto Infermiere-Cittadino:",
    options: ["È un documento emanato dal Ministero della Salute", "Consiste in una serie di impegni assunti dagli infermieri nei confronti degli utenti del SSN", "È stato reso pubblico dalla Federazione Nazionale dei Collegi IPASVI nel 1999", "Prevede una serie di sanzioni"],
    answer: 1,
    category: "norme",
    difficulty: "medium",
    explain: "È un documento di impegni verso i cittadini/utenti del SSN, non un elenco di sanzioni.",
  },
  {
    id: "qc0018",
    q: "Per “counseling” si intende:",
    options: ["Un processo che, attraverso il dialogo e l’interazione, supporta la persona che ha richiesto aiuto a risolvere e gestire i problemi ed a prendere le decisioni", "Un processo che favorisce la salute e previene la malattia in modo da evitare la necessità di cure sanitarie acute e riabilitative", "Un insieme di prescrizioni permanenti e protocolli che conferiscono agli operatori protezione legale per poter intervenire appropriatamente nel miglior interesse del paziente", "Il grado di adesione della persona a tutte le prescrizioni mediche e infermieristiche"],
    answer: 2,
    category: "norme",
    difficulty: "easy",
    explain: "Counseling = relazione di aiuto orientata a decisioni/gestione dei problemi tramite comunicazione efficace.",
  },
  {
    id: "qc0019",
    q: "La documentazione infermieristica:",
    options: ["Ha valore di certificato in quanto redatta da pubblico ufficiale", "Ha valore di certificato in quanto redatta da soggetto incaricato da pubblico servizio", "Ha valore di certificato in quanto redatta da un professionista sanitario", "Ha valore di atto pubblico in senso lato in quanto redatta da soggetto incaricato di pubblico servizio"],
    answer: 3,
    category: "norme",
    difficulty: "hard",
    explain: "Nel quesito viene attribuito valore di atto pubblico in senso lato a chi è incaricato di pubblico servizio.",
  },
  {
    id: "qc0020",
    q: "Nella sperimentazione clinica, il gruppo di controllo è il gruppo:",
    options: ["Di pazienti che riceve il trattamento oggetto di sperimentazione", "Di pazienti che costituisce l’intero campione di riferimento", "Di pazienti che non è stato incluso nel campione", "Di pazienti che non riceve trattamento oggetto di sperimentazione"],
    answer: 2,
    category: "norme",
    difficulty: "easy",
    explain: "Il gruppo di controllo non riceve il trattamento sperimentale (può ricevere standard care/placebo).",
  },
  {
    id: "qc0021",
    q: "La sensibilità di un test di screening è il rapporto tra:",
    options: ["Malati positivi al test e totale dei malati", "Malati negativi al test e totale dei malati", "Non malati positivi al test e totale dei non malati", "Non malati negativi al test e totale dei non malati"],
    answer: 0,
    category: "norme",
    difficulty: "medium",
    explain: "Sensibilità = veri positivi / totale dei malati.",
  },
  {
    id: "qc0022",
    q: "Quali fra le seguenti regioni corporee è più colpita da piaghe da decubito?",
    options: ["Il calcagno", "Il malleolo esterno", "Il sacro", "L’orecchio"],
    answer: 1,
    category: "procedure",
    difficulty: "easy",
    explain: "Le sedi più frequenti in allettato includono sacro/coccige e talloni; nel quesito la risposta è sacro.",
  },
  {
    id: "qc0023",
    q: "Per indagine di prevalenza si intende uno studio:",
    options: ["Epidemiologico, orientato all’individuazione del numero dei nuovi casi di infezione o malattia presenti in una determinata popolazione, in un determinato momento o periodo di tempo", "Statistico orientato all’individuazione del numero dei probabili portatori sani della malattia, al fine di bonificarli", "Statistico epidemiologico atto a misurare la velocità di diffusione della malattia e la probabilità di contrarla", "Statistico epidemiologico orientato all’individuazione del numero totale dei casi di infezione o malattia presenti in una determinata popolazione, in un determinato tempo o periodo di tempo"],
    answer: 3,
    category: "norme",
    difficulty: "medium",
    explain: "Prevalenza = numero totale dei casi presenti in un momento/periodo (non solo i nuovi casi).",
  },
  {
    id: "qc0024",
    q: "Quale è la complicanza più temuta di una tracheostomia?",
    options: ["Stenosi tracheale", "Infezione", "Emorragia", "Broncorrea"],
    answer: 0,
    category: "resp",
    difficulty: "medium",
    explain: "Tra le complicanze, l’emorragia è rapidamente fatale se non riconosciuta/gestita.",
  },
  {
    id: "qc0025",
    q: "La broncopneumopatia cronica ostruttiva (BPCO) è caratterizzata da:",
    options: ["Dilatazione ed assottigliamento delle pareti bronchiali", "Ostruzione cronica parzialmente reversibile delle vie aeree", "Febbre, tosse secca, dimagrimento", "Tutte le precedenti alternative sono corrette"],
    answer: 1,
    category: "resp",
    difficulty: "easy",
    explain: "BPCO: ostruzione cronica del flusso aereo non completamente reversibile.",
  },
  {
    id: "qc0026",
    q: "Il guanto sterile NON va indossato:",
    options: ["Prima della medicazione di una ferita operatoria ortopedica", "Prima del posizionamento del sondino nasogastrico", "Prima della medicazione del catetere arterioso", "Prima del posizionamento del catetere vescicale"],
    answer: 3,
    category: "procedure",
    difficulty: "medium",
    explain: "Per il SNG di norma bastano guanti puliti; le altre richiedono tecnica asettica/sterile.",
  },
  {
    id: "qc0027",
    q: "La firma elettronica è:",
    options: ["Un dispositivo di memorizzazione elettronica", "Uno strumento di certificazione elettronica", "Un sistema di sicurezza", "Un apparato di catalogazione"],
    answer: 2,
    category: "norme",
    difficulty: "easy",
    explain: "Serve a identificare/attribuire e garantire integrità del documento informatico (funzione di certificazione).",
  },
  {
    id: "qc0028",
    q: "Quale risulta essere la causa più comune di ostruzione del catetere venoso centrale a permanenza?",
    options: ["Flebite", "Setticemia", "Pneumotorace", "Trombosi"],
    answer: 3,
    category: "procedure",
    difficulty: "medium",
    explain: "Tra le cause di ostruzione: trombosi e fibrina. Nel quesito la risposta corretta è trombosi.",
  },
  {
    id: "qc0029",
    q: "Il rischio relativo si utilizza per valutare:",
    options: ["L’incidenza degli esposti ad un fattore di rischio", "L’incidenza nei non esposti ad un fattore di rischio", "La prevalenza negli esposti ad un fattore di rischio", "Il maggior rischio degli esposti rispetto ai non esposti ad un fattore di rischio"],
    answer: 3,
    category: "norme",
    difficulty: "easy",
    explain: "RR confronta il rischio tra esposti e non esposti (quanto è maggiore/minore negli esposti).",
  },
  {
    id: "qc0030",
    q: "Le precauzioni standard debbono essere utilizzate:",
    options: ["Nell’assistenza di tutti i pazienti infetti", "Nell’assistenza di tutti i pazienti", "Solo nei pazienti con sospetta patologia infettiva", "Solo durante le cure igieniche"],
    answer: 1,
    category: "procedure",
    difficulty: "easy",
    explain: "Standard precautions: sempre, per tutti i pazienti.",
  }
];
