export type QuizCategory = "antibiotici" | "farmaci" | "procedure" | "emergenza";
export type QuizQuestion = {
  id: string;
  q: string;
  options: string[];
  answer: number;
  category: QuizCategory;
};

export const QUIZ_BANK: QuizQuestion[] = [
  {
    id: "abx_1",
    q: "Qual è il principale meccanismo dei beta‑lattamici?",
    options: ["Inibizione sintesi proteica", "Inibizione parete cellulare", "Inibizione DNA/RNA", "Effetto antivirale"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "abx_2",
    q: "Quale classe è tipicamente associata a nefrotossicità e ototossicità?",
    options: ["Macrolidi", "Aminoglicosidi", "Penicilline", "Tetracicline"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "abx_3",
    q: "I glicopeptidi (es. vancomicina) coprono soprattutto:",
    options: ["Gram negativi", "Gram positivi", "Virus", "Funghi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "abx_4",
    q: "Le tetracicline possono dare come effetto avverso tipico:",
    options: ["Fotosensibilità", "Torsione di punta", "Iperpotassiemia", "Crisi ipertensiva"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "abx_5",
    q: "Le cefalosporine sono divise in generazioni principalmente per:",
    options: ["Via di eliminazione", "Spettro antimicrobico", "Costo", "Stabilità al calore"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "abx_6",
    q: "Quale antibiotico è tipicamente associato a rischio di colite da C. difficile?",
    options: ["Clindamicina", "Amoxicillina", "Azitromicina", "Nitrofurantoina"],
    answer: 0,
    category: "antibiotici",
  },
  {
    id: "abx_7",
    q: "I macrolidi agiscono principalmente:",
    options: ["Sulla subunità 50S", "Sulla subunità 30S", "Sulla parete cellulare", "Sui folati"],
    answer: 0,
    category: "antibiotici",
  },
  {
    id: "abx_8",
    q: "Fluorochinoloni: possibile effetto avverso rilevante:",
    options: ["Tendinopatia/rottura tendinea", "Ipertricosi", "Ipoglicemia sempre", "Ittero ostruttivo"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "abx_9",
    q: "Linezolid è attivo soprattutto contro:",
    options: ["MRSA e Gram+ resistenti", "Gram- non fermentanti", "Virus respiratori", "Funghi"],
    answer: 0,
    category: "antibiotici",
  },
  {
    id: "abx_10",
    q: "In allergia immediata a penicillina, per una faringite streptococcica si considera spesso:",
    options: ["Macrolide", "Aminoglicoside", "Carbapeneme", "Glicopeptide"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_1",
    q: "Quale classe può causare bradicardia e broncospasmo?",
    options: ["Beta-bloccanti", "Diuretici dell’ansa", "Statine", "Inibitori di pompa"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_2",
    q: "Un ACE-inibitore può dare:",
    options: ["Tosse secca", "Stipsi", "Sedazione marcata", "Ipertiroidismo"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_3",
    q: "Un anticoagulante orale diretto (DOAC) si usa per:",
    options: ["Prevenzione tromboembolica", "Trattare ipotiroidismo", "Dolore neuropatico", "Asma acuto"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_4",
    q: "La morfina può causare:",
    options: ["Depressione respiratoria", "Ipernatriemia", "Ipersudorazione sempre benefica", "Bradipnea assente"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_5",
    q: "Diuretici dell’ansa: esempio comune:",
    options: ["Furosemide", "Spironolattone", "Idroclorotiazide", "Acetazolamide"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_6",
    q: "Il paracetamolo è principalmente:",
    options: ["Analgesico/antipiretico", "Antibiotico", "Anticoagulante", "Antidepressivo"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_7",
    q: "Insulina rapida: rischio principale:",
    options: ["Ipoglicemia", "Ipercalcemia", "Ipernatriemia", "Alopecia"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_8",
    q: "Corticosteroidi sistemici possono causare:",
    options: ["Iperglicemia", "Ipoproteinemia immediata", "Bradicardia severa", "Iperpotassiemia sempre"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_9",
    q: "Un broncodilatatore beta2 può dare:",
    options: ["Tachicardia/tremori", "Bradicardia", "Miosi", "Ipotermia"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "farm_10",
    q: "Nitrati (es. nitroglicerina) sono usati soprattutto per:",
    options: ["Angina/ischemia", "Infezioni", "Anemia", "Ipertiroidismo"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "prc_1",
    q: "Prima di un prelievo arterioso, la cosa più importante da verificare è:",
    options: ["Gruppo sanguigno", "Allergia a iodio", "Adeguata perfusione collaterale (Allen test se indicato)", "Temperatura corporea"],
    answer: 2,
    category: "procedure",
  },
  {
    id: "prc_2",
    q: "Per ridurre emolisi nel prelievo venoso è utile:",
    options: ["Agitare vigorosamente la provetta", "Usare ago adeguato e riempire correttamente", "Lasciare il laccio >5 minuti", "Prelevare sempre da accesso periferico appena posizionato"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "prc_3",
    q: "In medicazione CVC, la priorità è:",
    options: ["Ridurre il tempo", "Mantenere tecnica asettica/sterile", "Usare sempre iodio", "Applicare crema antibiotica di routine"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "prc_4",
    q: "Flush 'push-pause' su CVC/PICC serve soprattutto a:",
    options: ["Aumentare pressione sempre", "Creare turbolenza per ridurre deposito fibrina", "Raffreddare il catetere", "Evitare dolore"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "prc_5",
    q: "Per prevenire lesioni da pressione bisogna:",
    options: ["Solo massaggiare le aree rosse", "Cambiare postura e usare presidi", "Applicare alcol quotidiano", "Tenere il paziente seduto"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "prc_6",
    q: "Per il controllo dolore toracico in triage, primo passo:",
    options: ["Somministrare morfina subito", "Valutazione ABC + ECG precoce", "Attendere esami del sangue", "Dare antibiotico"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "prc_7",
    q: "In caso di ipoglicemia sintomatica in paziente cosciente:",
    options: ["Insulina rapida", "Zuccheri a rapido assorbimento per os", "Solo acqua", "Sedazione"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "prc_8",
    q: "Quando si usa una cannula di Guedel:",
    options: ["In paziente vigile con riflesso del vomito", "Per mantenere vie aeree in incosciente senza riflessi protettivi", "Per aspirazione gastrica", "Per intubare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "prc_9",
    q: "La manovra di Heimlich è indicata in:",
    options: ["Ostruzione grave con incapacità di parlare/tossire", "Asma lieve", "Sincope", "Ipertensione"],
    answer: 0,
    category: "emergenza",
  },
  {
    id: "prc_10",
    q: "In shock anafilattico, farmaco di prima scelta:",
    options: ["Adrenalina IM", "Antistaminico per os", "Cortisone topico", "Paracetamolo"],
    answer: 0,
    category: "emergenza",
  },
  {
    id: "emg_1",
    q: "In caso di PEA (attività elettrica senza polso), la priorità è:",
    options: ["Defibrillare", "RCP + cause reversibili (Hs & Ts)", "Somministrare solo ossigeno", "Attendere il medico"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "emg_2",
    q: "Saturazione 82% in aria ambiente: primo intervento ragionevole:",
    options: ["Ossigeno e valutazione respiratoria", "Solo fluidi EV", "Antibiotico immediato", "Dimissione"],
    answer: 0,
    category: "emergenza",
  },
  {
    id: "emg_3",
    q: "Segno tipico di ipoperfusione:",
    options: ["Cute calda e sudata sempre", "Riempimento capillare lento", "Iperreflessia", "Miosi fissa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "emg_4",
    q: "Nel trauma, l’ABC significa:",
    options: ["Airway, Breathing, Circulation", "Analgesia, Blood, CT", "Antibiotics, Blood, Cardio", "Arterial, Brain, Chest"],
    answer: 0,
    category: "emergenza",
  },
  {
    id: "emg_5",
    q: "In arresto cardiaco con ritmo defibrillabile, l’intervento chiave è:",
    options: ["Defibrillazione + RCP", "Solo adrenalina", "Ventilazione senza compressioni", "Aspettare monitor"],
    answer: 0,
    category: "emergenza",
  },
  {
    id: "emg_6",
    q: "Iperpiressia (>40°C) in emergenza: prima misura:",
    options: ["Coperta termica", "Raffreddamento + valutazione cause", "Lasciare a riposo", "Solo antistaminico"],
    answer: 1,
    category: "emergenza",
  },


  // --- NurseDiary expanded bank (v2) ---
  {
    id: "nd_101",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_102",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_103",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_104",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_105",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_106",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_107",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_108",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_109",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_110",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_111",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_112",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_113",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_114",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_115",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_116",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_117",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_118",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_119",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_120",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_121",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_122",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_123",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_124",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_125",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_126",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_127",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_128",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_129",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_130",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_131",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_132",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_133",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_134",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_135",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_136",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_137",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_138",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_139",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_140",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_141",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_142",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_143",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_144",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_145",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_146",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_147",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_148",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_149",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_150",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_151",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_152",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_153",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_154",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_155",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_156",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_157",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_158",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_159",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_160",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_161",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_162",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_163",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_164",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_165",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_166",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_167",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_168",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_169",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_170",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_171",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_172",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_173",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_174",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_175",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_176",
    q: "In caso di sospetta anafilassi, la prima terapia di scelta è:",
    options: ["Antistaminico orale", "Adrenalina IM", "Cortisonico EV immediato", "Ossigeno a basso flusso e attesa"],
    answer: 1,
    category: "emergenza",
  },
  {
    id: "nd_177",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_178",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_179",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_180",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_181",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_182",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_183",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_184",
    q: "In BLS, la frequenza delle compressioni toraciche nell'adulto è circa:",
    options: ["60/min", "80/min", "100-120/min", "140/min"],
    answer: 2,
    category: "emergenza",
  },
  {
    id: "nd_185",
    q: "Quale accesso venoso è preferibile per infusioni vescicanti prolungate?",
    options: ["Ago a farfalla", "CVC/PICC", "IM", "Sottocute"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_186",
    q: "Quale parametro va controllato con eparina (non frazionata) in infusione?",
    options: ["INR", "aPTT", "Creatinina", "Glicemia"],
    answer: 1,
    category: "farmaci",
  },
  {
    id: "nd_187",
    q: "In una medicazione CVC, qual è il primo passo prima di toccare il sito?",
    options: ["Indossare guanti sterili senza igiene mani", "Igiene mani accurata", "Applicare subito garza", "Soffiare per asciugare"],
    answer: 1,
    category: "procedure",
  },
  {
    id: "nd_188",
    q: "Con digossina, quale segno può indicare tossicità?",
    options: ["Visione gialla/alterata", "Ipertermia", "Polidipsia", "Rash fotosensibile"],
    answer: 0,
    category: "farmaci",
  },
  {
    id: "nd_189",
    q: "Per ridurre resistenze, l'uso degli antibiotici dovrebbe basarsi su:",
    options: ["Terapia empirica prolungata", "Antibiogramma quando disponibile", "Dose minima sempre", "Solo macrolidi"],
    answer: 1,
    category: "antibiotici",
  },
  {
    id: "nd_190",
    q: "La vancomicina è principalmente attiva contro:",
    options: ["Gram negativi", "Gram positivi", "Virus influenzali", "Protozoi"],
    answer: 1,
    category: "antibiotici",
  },
];
