export type QuizCategory = "antibiotici" | "farmaci" | "procedure" | "emergenza";
export type QuizDifficulty = "easy" | "medium" | "hard";

export type QuizQuestion = {
  id: string;
  q: string;
  options: string[];
  answer: number;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  explain: string;
};

// ✅ Banca domande v2 (50)
// - scenari brevi
// - 4 opzioni plausibili
// - spiegazione sintetica (educativa)
export const QUIZ_BANK: QuizQuestion[] = [
  {
    id: "q1001",
    q: "Dopo la rimozione dei guanti e il contatto con superfici del paziente, quale azione è corretta prima di uscire dalla stanza?",
    options: ["Indossare nuovi guanti", "Igiene delle mani", "Toccare il telefono", "Mettere solo la mascherina"],
    answer: 1,
    category: "procedure",
    difficulty: "easy",
    explain: "I guanti non sostituiscono l'igiene delle mani: va eseguita dopo la rimozione e dopo contatto con ambiente del paziente.",
  },
  {
    id: "q1002",
    q: "Emocoltura periferica: dopo la disinfezione della cute, cosa va evitato per ridurre contaminazione?",
    options: ["Attendere asciugatura", "Ripalpazione del sito", "Etichettare correttamente", "Usare tecnica asettica"],
    answer: 1,
    category: "procedure",
    difficulty: "medium",
    explain: "Ripalpando dopo l'antisepsi reintroduci flora cutanea e aumenti contaminazioni.",
  },
  {
    id: "q1003",
    q: "Trasfusione: qual è il controllo più critico prima di iniziare l'infusione?",
    options: ["Peso", "Glicemia", "Identità paziente + compatibilità", "Diuresi"],
    answer: 2,
    category: "procedure",
    difficulty: "easy",
    explain: "La corretta identificazione e compatibilità previene eventi avversi gravi.",
  },
  {
    id: "q1004",
    q: "Sospetta reazione trasfusionale (brividi, febbre, dispnea): prima azione?",
    options: ["Aumentare la velocità", "Interrompere trasfusione e mantenere accesso con fisiologica", "Rimuovere accesso venoso", "Somministrare antipiretico e continuare"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Stop immediato limita l'esposizione; poi gestione secondo setting/protocollo.",
  },
  {
    id: "q1005",
    q: "Infusione EV: quale triade è più suggestiva di infiltrazione?",
    options: ["Gonfiore + dolore + cute fredda", "Febbre + tosse", "Cefalea + nausea", "Ipertensione + bradicardia"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Infiltrazione: fuoriuscita nel tessuto → edema, dolore, cute fredda/pallida.",
  },
  {
    id: "q1006",
    q: "SpO₂ 84% con distress respiratorio: priorità iniziale (ABCDE)?",
    options: ["Prelievo venoso", "ECG", "Ossigeno e rivalutazione", "Idratazione orale"],
    answer: 2,
    category: "emergenza",
    difficulty: "easy",
    explain: "In ABCDE la priorità è la respirazione: ossigeno/monitoraggio ed escalation se serve.",
  },
  {
    id: "q1007",
    q: "Quale valore è più compatibile con ipoglicemia sintomatica?",
    options: ["58 mg/dL", "98 mg/dL", "145 mg/dL", "210 mg/dL"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "<70 mg/dL è ipoglicemia; con sintomi va trattata rapidamente nel tuo setting.",
  },
  {
    id: "q1008",
    q: "Eparina SC: sede più comune e corretta?",
    options: ["Addome (rotazione siti)", "Collo", "Polpaccio", "Avambraccio"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Sede tipica: addome; evitare massaggio e ruotare i siti.",
  },
  {
    id: "q1009",
    q: "Quale associazione aumenta rischio di sanguinamento?",
    options: ["FANS + anticoagulante", "Paracetamolo + PPI", "Amoxicillina + acqua", "Metformina + vitamina C"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "FANS con anticoagulanti/antiaggreganti aumenta rischio emorragico (soprattutto GI).",
  },
  {
    id: "q1010",
    q: "Macrolidi: quale rischio è noto (soprattutto con predisposizione)?",
    options: ["Allungamento QT", "Iperuricemia", "Nefrotossicità severa", "Iperkaliemia"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Alcuni macrolidi possono prolungare il QT e aumentare rischio aritmie.",
  },
  {
    id: "q1011",
    q: "Fluorochinoloni: quale effetto avverso tipico?",
    options: ["Tendinopatia", "Ipernatriemia", "Bradicardia marcata", "Ipoacusia immediata sempre"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Rischio tendinite/rottura tendinea, soprattutto anziani o con corticosteroidi.",
  },
  {
    id: "q1012",
    q: "BPCO con ipercapnia nota: target SpO₂ spesso usato?",
    options: ["98–100%", "94–98%", "88–92%", "75–80%"],
    answer: 2,
    category: "procedure",
    difficulty: "hard",
    explain: "Spesso si mira a 88–92% per ridurre rischio di ipercapnia (secondo indicazione clinica).",
  },
  {
    id: "q1013",
    q: "Quale segno è più suggestivo di ipovolemia/ipoperfusione?",
    options: ["Cute calda e arrossata", "Tachicardia + ipotensione + refill lento", "Bradicardia", "SpO₂ 100%"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Segni di shock: tachicardia, ipotensione e ipoperfusione periferica.",
  },
  {
    id: "q1014",
    q: "Sepsi: quale è un segno precoce che richiede attenzione/escalation?",
    options: ["FR aumentata + confusione", "Cute rosea", "Afebbrile e vigile", "Dolore lieve"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Tachipnea e alterazione dello stato mentale possono essere segni precoci di deterioramento.",
  },
  {
    id: "q1015",
    q: "CAUTI: quale misura riduce maggiormente il rischio?",
    options: ["Sistema chiuso + rimozione precoce", "Irrigazioni frequenti", "Sostituire ogni giorno", "Sacca sopra la vescica"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "Durata minima, sistema chiuso e corretta gestione della sacca riducono CAUTI.",
  },
  {
    id: "q1016",
    q: "Sindrome serotoninergica: quale combinazione aumenta il rischio?",
    options: ["SSRI + IMAO/triptani", "PPI + paracetamolo", "Beta-bloccante + diuretico", "Amoxicillina + probiotico"],
    answer: 0,
    category: "farmaci",
    difficulty: "hard",
    explain: "Più farmaci serotoninergici insieme aumentano rischio (attenzione anche a linezolid).",
  },
  {
    id: "q1017",
    q: "Lesioni da pressione: quale intervento è corretto?",
    options: ["Mobilizzazione + superfici adeguate + ispezione cute", "Massaggiare l'eritema", "Stessa posizione prolungata", "Talco su cute umida"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Prevenzione: ridurre pressione/umidità, mobilizzare e controllare cute regolarmente.",
  },
  {
    id: "q1018",
    q: "Estravaso di farmaco vescicante: quale segno è tipico?",
    options: ["Bruciore locale + edema", "Tosse", "Cefalea", "Febbre immediata"],
    answer: 0,
    category: "farmaci",
    difficulty: "hard",
    explain: "Dolore/bruciore e edema al sito richiedono gestione immediata secondo protocollo locale.",
  },
  {
    id: "q1019",
    q: "Accesso intraosseo: quando è più indicato?",
    options: ["Accesso EV non ottenibile rapidamente in emergenza", "Per terapia cronica", "Per prelievi routinari", "Per trasfusioni elettive"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "È un'alternativa rapida quando l'accesso EV è difficile/impossibile in contesto critico.",
  },
  {
    id: "q1020",
    q: "Anaphylaxis: segno che aumenta urgenza?",
    options: ["Orticaria isolata", "Stridore/dispnea + ipotensione", "Prurito lieve", "Sola nausea"],
    answer: 1,
    category: "emergenza",
    difficulty: "hard",
    explain: "Coinvolgimento respiratorio/circolatorio = emergenza: attiva percorso e gestione immediata.",
  },

  // --- Antibiotici ---
  {
    id: "q1021",
    q: "Penicillina: quale reazione suggerisce allergia immediata (IgE-mediata)?",
    options: ["Orticaria/dispnea entro minuti", "Nausea lieve", "Diarrea tardiva", "Cefalea"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Sintomi rapidi (orticaria, broncospasmo, angioedema) suggeriscono reazione IgE.",
  },
  {
    id: "q1022",
    q: "Vancomicina: quale evento è tipico se infusa troppo rapidamente?",
    options: ["Red man syndrome", "Iperglicemia", "Crisi ipertensiva", "Bradicardia riflessa"],
    answer: 0,
    category: "antibiotici",
    difficulty: "hard",
    explain: "Rossore/prurito e ipotensione possono comparire con infusione rapida: rallentare e gestire.",
  },
  {
    id: "q1023",
    q: "C. difficile: quale antibiotico è spesso associato a rischio aumentato di diarrea/colite?",
    options: ["Clindamicina", "Amoxicillina singola dose", "Fosfomicina", "Rifampicina"],
    answer: 0,
    category: "antibiotici",
    difficulty: "hard",
    explain: "Clindamicina e antibiotici ad ampio spettro aumentano rischio di C. difficile.",
  },
  {
    id: "q1024",
    q: "Aminoglicosidi: quale tossicità è classica?",
    options: ["Nefro/ototossicità", "Iperkaliemia", "Ipertermia", "Ipertensione"],
    answer: 0,
    category: "antibiotici",
    difficulty: "hard",
    explain: "Aminoglicosidi possono essere nefro- e ototossici: monitorare secondo prescrizione.",
  },
  {
    id: "q1025",
    q: "Cefalosporine: quale è un punto corretto su allergia crociata con penicilline?",
    options: ["Dipende dalla storia e dal tipo di reazione", "È sempre 100%", "Non esiste mai", "È uguale per tutte le generazioni"],
    answer: 0,
    category: "antibiotici",
    difficulty: "hard",
    explain: "Il rischio varia: conta il tipo di reazione e le strutture laterali (da valutare clinicamente).",
  },

  // --- Farmaci ---
  {
    id: "q1026",
    q: "Oppioidi: quale effetto avverso richiede monitoraggio stretto?",
    options: ["Depressione respiratoria", "Aumento appetito", "Ipertermia", "Ipertricosi"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Il rischio più pericoloso è la depressione respiratoria: monitorare FR, SpO₂ e sedazione.",
  },
  {
    id: "q1027",
    q: "Insulina rapida: quale è la verifica più importante prima di somministrarla?",
    options: ["Glicemia capillare", "Temperatura", "Diuresi", "Peso"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "La dose di insulina rapida dipende dalla glicemia e dallo schema prescritto.",
  },
  {
    id: "q1028",
    q: "Warfarin: quale esame di laboratorio è tipicamente monitorato?",
    options: ["INR", "aPTT", "PCR", "Creatinina"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "Il warfarin richiede monitoraggio INR per efficacia e sicurezza.",
  },
  {
    id: "q1029",
    q: "Diuretico dell'ansa (es. furosemide): quale parametro è utile monitorare?",
    options: ["Diuresi e potassio", "Solo temperatura", "Solo glicemia", "Solo saturazione"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Rischio disidratazione e ipokaliemia: controllare bilancio e elettroliti.",
  },
  {
    id: "q1030",
    q: "Beta-bloccanti: quale effetto avverso può comparire?",
    options: ["Bradicardia", "Iperventilazione", "Ipertermia", "Aumento immediato diuretic"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "Bradicardia e ipotensione sono effetti possibili: monitorare FC/PA.",
  },

  // --- Procedure ---
  {
    id: "q1031",
    q: "Somministrazione IM: quale sede è tipicamente preferita nell'adulto per volumi maggiori?",
    options: ["Ventroglutea", "Radio", "Polso", "Caviglia"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "La sede ventroglutea è spesso preferita per sicurezza anatomica e buon volume.",
  },
  {
    id: "q1032",
    q: "Prelievo: perché l'ordine delle provette è importante?",
    options: ["Riduce contaminazione da additivi", "Solo estetica", "Accelera la coagulazione", "Evita lipemia"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "L'ordine riduce carry-over di additivi tra provette che altererebbe i risultati.",
  },
  {
    id: "q1033",
    q: "Sonda NG: prima di somministrare terapia/alimentazione, cosa verifichi?",
    options: ["Posizionamento secondo procedura del tuo reparto", "Solo colore della sonda", "Solo dolore", "Niente: vai"],
    answer: 0,
    category: "procedure",
    difficulty: "hard",
    explain: "Verifica del posizionamento secondo pratica locale (metodi accettati nel tuo setting) è essenziale.",
  },
  {
    id: "q1034",
    q: "Ossigeno: quale dispositivo è più adatto per FiO₂ precisa?",
    options: ["Venturi", "Cannule nasali sempre", "Solo maschera semplice", "Nessuno"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "La Venturi consente FiO₂ più controllata rispetto a cannule/maschera semplice.",
  },
  {
    id: "q1035",
    q: "Tracheostomia: qual è una priorità in caso di secrezioni abbondanti?",
    options: ["Aspirazione e pervietà vie aeree", "Bere acqua", "Camminare", "Sospendere monitor"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "La priorità è mantenere pervie le vie aeree; l'aspirazione va eseguita correttamente.",
  },

  // --- Emergenza ---
  {
    id: "q1036",
    q: "Stroke sospetto: quale è un comportamento corretto?",
    options: ["Attivare percorso ictus e registrare ora esordio", "Attendere che migliori", "Dare da bere", "Far alzare il paziente"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Tempo = cervello: attiva percorso e annota last known well/esordio.",
  },
  {
    id: "q1037",
    q: "Shock anafilattico: quale farmaco è tipicamente di prima linea?",
    options: ["Adrenalina IM", "Paracetamolo", "Furosemide", "Omeprazolo"],
    answer: 0,
    category: "emergenza",
    difficulty: "hard",
    explain: "L'adrenalina IM è spesso il trattamento di prima linea (nel setting appropriato).",
  },
  {
    id: "q1038",
    q: "Convulsioni in corso: cosa è più importante all'inizio?",
    options: ["Proteggere da traumi e mantenere vie aeree", "Bloccare gli arti", "Mettere oggetti in bocca", "Dare acqua"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Sicurezza del paziente e ABC: protezione, posizione, ossigeno/monitoraggio se indicato.",
  },
  {
    id: "q1039",
    q: "PA 80/50 con segni di ipoperfusione: quale azione è coerente con ABCDE?",
    options: ["Valutazione rapida + accesso/monitor + escalation", "Aspettare 30 minuti", "Solo analgesico", "Dimettere"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Ipotensione con segni di shock richiede valutazione rapida, monitor e attivazione supporto.",
  },
  {
    id: "q1040",
    q: "Iperpiressia: quale rischio va considerato?",
    options: ["Disidratazione e aumento consumo di O₂", "Solo prurito", "Solo ipoglicemia", "Nessuno"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Febbre alta aumenta consumo metabolico e rischio disidratazione: monitorare e trattare.",
  },

  // --- Mix (resto fino a 50) ---
  {
    id: "q1041",
    q: "Catetere venoso periferico: quando va rivalutata la necessità?",
    options: ["Ogni giorno / a ogni turno", "Solo a dimissione", "Mai", "Solo se fa male"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Rivalutazione frequente riduce infezioni e complicanze legate al dispositivo.",
  },
  {
    id: "q1042",
    q: "Anticoagulanti: quale segno clinico può indicare sanguinamento occulto?",
    options: ["Melena", "Cute secca", "Bradipnea", "Miosi"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Melena può indicare sanguinamento GI: va riferito e valutato.",
  },
  {
    id: "q1043",
    q: "Antibiotico EV: prima di somministrare, quale verifica è essenziale?",
    options: ["Allergie documentate e prescrizione corretta", "Solo colore flacone", "Solo pressione", "Solo temperatura"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "Allergie e corretta prescrizione (farmaco/dose/tempo) sono fondamentali per sicurezza.",
  },
  {
    id: "q1044",
    q: "Farmaci: quale situazione richiede particolare cautela con sedativi/oppiodi?",
    options: ["FR bassa o sonnolenza marcata", "Appetito aumentato", "Sete", "Mild rash"],
    answer: 0,
    category: "farmaci",
    difficulty: "hard",
    explain: "Rischio depressione respiratoria: monitorare FR, sedazione e saturazione.",
  },
  {
    id: "q1045",
    q: "Procedure: perché è importante l'asciugatura dell'antisettico prima di una puntura?",
    options: ["Aumenta efficacia e riduce contaminazione", "Serve solo a non bagnare", "Riduce dolore sempre", "Non è importante"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "Molti antisettici necessitano tempo di contatto/asciugatura per massima efficacia.",
  },
  {
    id: "q1046",
    q: "Se un paziente è improvvisamente soporoso, qual è una valutazione rapida utile?",
    options: ["Glicemia + parametri + stato neurologico", "Solo temperatura", "Solo dolore", "Solo altezza"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Alterazione coscienza: valuta glicemia, ABC, parametri e causa reversibile.",
  },
  {
    id: "q1047",
    q: "Antibiotici: quale misura riduce rischio di resistenza?",
    options: ["Uso appropriato e completamento secondo prescrizione", "Interrompere appena migliora", "Dosi casuali", "Condividerlo con altri"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "Aderenza e appropriatezza sono chiave per efficacia e riduzione resistenze.",
  },
  {
    id: "q1048",
    q: "Farmaci: quale segno può suggerire reazione avversa grave (anafilassi) dopo somministrazione?",
    options: ["Dispnea/stridore e ipotensione", "Leggera sonnolenza", "Bocca secca", "Aumento appetito"],
    answer: 0,
    category: "farmaci",
    difficulty: "hard",
    explain: "Coinvolgimento respiratorio/circolatorio richiede gestione urgente.",
  },
  {
    id: "q1049",
    q: "Procedura: quali sono due siti a rischio per lesioni da pressione in allettati?",
    options: ["Sacrum e talloni", "Mani e naso", "Orecchie e dita", "Spalle e gomiti sempre"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Sacrum e talloni sono tra le sedi più frequenti: prevenzione mirata.",
  },
  {
    id: "q1050",
    q: "Emergenza: paziente con dolore toracico + sudorazione: quale azione infermieristica iniziale è appropriata?",
    options: ["Valuta parametri/dolore, monitor e attiva percorso", "Attendi che passi", "Dai cibo", "Fai camminare"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Valutazione rapida, monitoraggio e attivazione percorso secondo setting.",
  },


// ✅ Banca domande v3 (+50)
// - scenari clinici realistici
// - opzioni plausibili
// - spiegazioni sintetiche
  {
    id: "q1051",
    q: "In un paziente con SpO₂ 90% in BPCO stabile, quale target è generalmente appropriato?",
    options: ["88–92%", "94–98%", "100%", "Non somministrare mai O₂"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Nei pazienti BPCO a rischio di ipercapnia spesso si mira a 88–92%, salvo diversa indicazione clinica.",
  },
  {
    id: "q1052",
    q: "Durante somministrazione di noradrenalina in siringa, quale accesso è preferibile se disponibile?",
    options: ["CVC dedicato", "IM", "Sottocute", "Orale"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Vasopressori preferibilmente via CVC (riduce rischio extravasazione); se periferico: calibro grande, sede prossimale, monitoraggio stretto.",
  },
  {
    id: "q1053",
    q: "Qual è il primo controllo se un paziente in infusione di insulina presenta sudorazione e tremori?",
    options: ["Glicemia capillare", "PA", "Temperatura", "ECG"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "Sintomi compatibili con ipoglicemia: controlla subito la glicemia e tratta secondo protocollo.",
  },
  {
    id: "q1054",
    q: "Dopo prelievo per emocolture, quale comportamento è corretto per ridurre contaminazioni?",
    options: ["Disinfezione accurata e rispetto tempi di asciugatura", "Toccare il tappo dopo disinfezione", "Prelevare da catetere senza scartare", "Agitare energicamente le bottiglie"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "La contaminazione diminuisce con antisepsi corretta e lasciando asciugare l’antisettico; evita ricontaminazioni.",
  },
  {
    id: "q1055",
    q: "Un paziente in terapia con eparina EV ha piastrine in calo e trombosi: sospetto principale?",
    options: ["HIT (trombocitopenia indotta da eparina)", "CID", "Allergia al lattice", "Ipervitaminosi K"],
    answer: 0,
    category: "farmaci",
    difficulty: "hard",
    explain: "Calo piastrine + trombosi in eparina suggerisce HIT: sospendere eparina e avvisare il medico per anticoagulante alternativo.",
  },
  {
    id: "q1056",
    q: "In un paziente con dolore toracico e ST elevato, quale farmaco è spesso prioritario se non controindicato?",
    options: ["Aspirina", "Paracetamolo", "Loperamide", "Furosemide"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Nell’ACS, l’aspirina è spesso somministrata precocemente se non controindicata.",
  },
  {
    id: "q1057",
    q: "Quale segno richiede rivalutazione immediata del sito di un accesso venoso periferico durante infusione di KCl?",
    options: ["Bruciore/dolore e tumefazione", "Leggera sete", "Starnuti", "Prurito al cuoio capelluto"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "KCl è irritante: dolore, edema o arrossamento possono indicare stravaso/flebite e richiedono stop e valutazione.",
  },
  {
    id: "q1058",
    q: "Se un paziente in ossigenoterapia peggiora con sonnolenza e ipoventilazione, quale sospetti per primo?",
    options: ["Ritenzione di CO₂/iper-capnia", "Ipernatriemia", "Ipokalemia", "Ipertermia maligna"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Sonnolenza e ipoventilazione possono indicare ipercapnia: valuta emogas e adegua ossigeno/ventilazione.",
  },
  {
    id: "q1059",
    q: "Quale procedura riduce il rischio di occlusione di un CVC dopo somministrazione di farmaci incompatibili?",
    options: ["Flush con soluzione appropriata tra farmaci", "Aumentare la velocità del farmaco successivo", "Usare sempre la stessa luce", "Non usare mai clamp"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Il flush tra farmaci riduce precipitati e occlusioni, soprattutto se incompatibili.",
  },
  {
    id: "q1060",
    q: "In caso di anafilassi, quale via è raccomandata per adrenalina di prima scelta?",
    options: ["IM (anterolaterale coscia)", "EV bolo rapido sempre", "Orale", "SC"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Nell’anafilassi, adrenalina IM nella coscia è la prima scelta; EV riservata a contesti monitorati/critici.",
  },
  {
    id: "q1061",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1062",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1063",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1064",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1065",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1066",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1067",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1068",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1069",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1070",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1071",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1072",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1073",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1074",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1075",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1076",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1077",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1078",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1079",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1080",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1081",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1082",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1083",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1084",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1085",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1086",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1087",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1088",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1089",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1090",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1091",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1092",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1093",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1094",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1095",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1096",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1097",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1098",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1099",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1100",
    q: "Qual è l'azione più corretta quando una pompa infusione segnala 'occlusione' e il paziente è stabile?",
    options: ["Controllare linea/sito, clamp e pieghe, poi riprendere se ok", "Ignorare e silenziare l'allarme", "Aumentare la pressione della pompa al massimo", "Rimuovere l'accesso senza valutazione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Verifica meccanica (pieghe, clamp, raccordi) e il sito; poi riprendi solo se tutto è regolare e monitori.",
  },
  {
    id: "q1101",
    q: "Shock settico in valutazione: qual è un obiettivo iniziale spesso utilizzato per MAP?",
    options: ["MAP ≥ 65 mmHg", "MAP ≥ 95 mmHg", "MAP ≥ 40 mmHg", "MAP ≥ 110 mmHg"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Target iniziale spesso usato: MAP ≥65 mmHg, poi personalizzare (età, comorbidità, target perfusione).",
  },
  {
    id: "q1102",
    q: "Paziente con dolore toracico e sudorazione: qual è una priorità operativa iniziale?",
    options: ["ECG 12 derivazioni il prima possibile", "Somministrare cibo", "Aspettare che passi", "Fisioterapia respiratoria"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Dolore toracico sospetto: ECG precoce guida diagnosi/percorsi (STEMI/NSTEMI).",
  },
  {
    id: "q1103",
    q: "Quale segno è più suggestivo di stravaso da farmaco vescicante?",
    options: ["Dolore/bruciore intenso + edema + eritema", "Polso radiale forte", "Mucose secche", "Ittero"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "Vescicanti: dolore/bruciore, edema, eritema; interrompere, aspirare se possibile e gestire secondo protocollo locale.",
  },
  {
    id: "q1104",
    q: "Quale combinazione aumenta il rischio di iperkaliemia?",
    options: ["ACE-inibitore + spironolattone", "Paracetamolo + PPI", "Amoxicillina + probiotico", "Furosemide + KCl (monitorato)"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "ACEi/ARB + risparmiatori di K (es. spironolattone) aumenta rischio iperkaliemia: monitorare K e funzione renale.",
  },
  {
    id: "q1105",
    q: "Antibiotici beta-lattamici: quale evento avverso va temuto in paziente con anamnesi di anafilassi a penicillina?",
    options: ["Reazione allergica immediata", "Iperglicemia", "Ipernatriemia", "Bradipnea"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "In caso di anafilassi documentata a penicillina, valutare cross-reattività e alternative secondo indicazione medica.",
  },
  {
    id: "q1106",
    q: "Se la SpO₂ è bassa ma il paziente ha dita fredde e movimento, quale controllo aiuta a validare il dato?",
    options: ["Verificare segnale pleth/posizionamento e ripetere su altro dito", "Cambiare termometro", "Misurare pressione sul polso", "Aumentare luminosità schermo"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Ossimetro può dare falsi bassi con perfusione scarsa/movimento: controlla qualità segnale e ripeti.",
  },
  {
    id: "q1107",
    q: "Insulina rapida in ipoglicemia severa: quale approccio è più corretto?",
    options: ["Non somministrare insulina; trattare ipoglicemia", "Aumentare dose di insulina", "Solo acqua", "Sospendere monitoraggio"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "In ipoglicemia severa la priorità è correggere la glicemia (glucosio/terapia secondo setting) e rivalutare.",
  },
  {
    id: "q1108",
    q: "Quale parametro è più utile per valutare trend di perfusione periferica?",
    options: ["Tempo di refill capillare", "Colore dei capelli", "Acuità visiva", "Lunghezza unghie"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Capillary refill e temperatura cutanea aiutano nella valutazione rapida della perfusione periferica.",
  },
  {
    id: "q1109",
    q: "CVC: quale azione riduce maggiormente il rischio di infezione correlata al catetere?",
    options: ["Igiene mani + tecnica asettica in accesso/manipolazione", "Cambiare cerotto ogni giorno senza motivo", "Usare sempre la stessa siringa", "Non disinfettare mai i raccordi"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Bundle: igiene mani, disinfezione hub, tecnica asettica, medicazione corretta e valutazione necessità del CVC.",
  },
  {
    id: "q1110",
    q: "In caso di bradicardia sintomatica (ipotensione, sincope), cosa è prioritario?",
    options: ["Valutare ABCDE e monitor/ECG", "Solo bere acqua", "Dimettere subito", "Camminare per aumentare FC"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Bradicardia sintomatica: valutazione ABCDE, monitoraggio e gestione secondo setting/percorsi.",
  },
  {
    id: "q1111",
    q: "Sospetta sepsi: quale coppia di azioni è più coerente nelle fasi iniziali?",
    options: ["Prelievi/colture (se indicato) + avvio terapia secondo prescrizione", "Aspettare 24h", "Solo antipiretico", "Solo fisioterapia"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Nelle prime fasi: valutazione rapida, prelievi mirati e avvio terapia (fluidi/antibiotico) secondo indicazione.",
  },
  {
    id: "q1112",
    q: "Vancomicina EV: quale monitoraggio è spesso importante?",
    options: ["Funzione renale e livelli (se previsti)", "Solo temperatura", "Solo saturazione", "Solo glicemia"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Vancomicina: nefrotossicità possibile; in molti contesti si monitorano creatinina e livelli (AUC/trough) se previsti.",
  },
  {
    id: "q1113",
    q: "Ceftriaxone: quale compatibilità va evitata per rischio precipitazione?",
    options: ["Co-infusione con calcio", "Con fisiologica", "Con glucosata", "Con acqua per preparazioni"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Ceftriaxone + calcio può precipitare (rischio maggiore in neonati). Evitare co-infusione nella stessa linea.",
  },
  {
    id: "q1114",
    q: "Quale indicazione è corretta per l'uso di naloxone in sospetta overdose da oppioidi?",
    options: ["Depressione respiratoria: somministrazione secondo protocollo/indicazione", "Dolore addominale", "Febbre", "Ipertensione isolata"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Naloxone è un antagonista oppioide: si usa per depressione respiratoria/sedazione importante secondo setting.",
  },
  {
    id: "q1115",
    q: "Quale intervento riduce il rischio di aspirazione in paziente soporoso?",
    options: ["Posizionamento e protezione vie aeree secondo valutazione", "Dare acqua a piccoli sorsi", "Solo coperta", "Alzare le gambe"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Se coscienza ridotta: valutare protezione vie aeree, posizione di sicurezza se appropriato e attivare percorso.",
  },
  {
    id: "q1116",
    q: "Eparina SC: quale pratica è corretta?",
    options: ["Non massaggiare il sito dopo l'iniezione", "Massaggiare energicamente", "Iniettare sempre nello stesso punto", "Aspirare sempre"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Non massaggiare riduce ematomi; ruotare siti e usare tecnica corretta secondo linee locali.",
  },
  {
    id: "q1117",
    q: "Un paziente in ossigenoterapia peggiora la dispnea: quale verifica è immediata?",
    options: ["Controllo dispositivo/flussometro e pervietà", "Solo cambiare reparto", "Spegnere ossigeno", "Dare solo acqua"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Prima: verifica tecnica (flusso, connessioni, maschera/cannule) e rivaluta parametri.",
  },
  {
    id: "q1118",
    q: "Quale è un segno precoce di ipossia?",
    options: ["Tachicardia e agitazione", "Unghie lunghe", "Polso forte", "Cute calda"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Ipossia può dare tachicardia, agitazione, ansia, confusione e poi cianosi più tardiva.",
  },
  {
    id: "q1119",
    q: "Antibiotico in infusione: quale comportamento riduce rischi di incompatibilità con altri farmaci?",
    options: ["Usare linea dedicata o flush prima/dopo", "Collegare tutto allo stesso rubinetto senza flush", "Mescolare in siringa", "Aumentare concentrazione"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "Linea dedicata/flush riduce precipitati e incompatibilità in Y-site.",
  },
  {
    id: "q1120",
    q: "Quale farmaco è noto per rischio di prolungamento QT (classe)?",
    options: ["Macrolidi", "Vitamina D", "Lattulosio", "Soluzione fisiologica"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Diversi farmaci (es. macrolidi) possono prolungare QT: attenzione in predisposti e con altri farmaci QT.",
  },
  {
    id: "q1121",
    q: "Piperacillina/tazobactam EV: quale parametro è spesso importante monitorare in terapia prolungata?",
    options: ["Funzione renale", "Colore dei capelli", "Forza di presa", "Acuità visiva"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "Molti antibiotici richiedono aggiustamento su funzione renale; monitoraggio clinico-laboratoristico secondo setting.",
  },
  {
    id: "q1122",
    q: "In caso di ipotensione con segni di shock, quale è una priorità?",
    options: ["Monitoraggio e accesso venoso rapido", "Solo misurare temperatura", "Solo riposo", "Solo dieta"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Shock: valutazione ABCDE, monitor, accesso EV, fluidi/vasopressori secondo indicazione e causa.",
  },
  {
    id: "q1123",
    q: "Quale segno può indicare peggioramento neurologico acuto?",
    options: ["Nuova confusione/sonnolenza", "Sete", "Prurito", "Mialgia"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Alterazione acuta dello stato mentale è un red flag: rivalutazione e escalation.",
  },
  {
    id: "q1124",
    q: "Somministrazione di KCl EV: quale precauzione è corretta?",
    options: ["Somministrare in infusione controllata (non bolo)", "Bolo rapido", "Sempre IM", "Mai monitorare ECG"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "KCl EV va in infusione controllata con monitoraggio secondo setting: rischio aritmie se rapido.",
  },
  {
    id: "q1125",
    q: "In caso di vomito in paziente con rischio aspirazione, quale posizione è spesso utile?",
    options: ["Laterale di sicurezza (se appropriato)", "Supina piatta", "Trendelenburg", "Prona sempre"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Posizione laterale può ridurre aspirazione; sempre valutare condizioni e vie aeree.",
  },
  {
    id: "q1126",
    q: "Quale indicazione è corretta per l'uso della scala GCS?",
    options: ["Valuta occhi, verbale, motoria e segue trend", "È solo per bambini", "Si usa solo una volta", "Non serve documentare"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "GCS è utile per trend neurologico; documentare componenti (E/V/M) oltre al totale.",
  },
  {
    id: "q1127",
    q: "Quale è una reazione avversa tipica da infusione rapida di vancomicina?",
    options: ["Red man syndrome (flush/eritema)", "Ipernatriemia acuta", "Iperuricemia", "Ictus"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Infusione troppo rapida può dare flushing/eritema e prurito: ridurre velocità e gestire secondo prescrizione.",
  },
  {
    id: "q1128",
    q: "In caso di febbre dopo trasfusione: prima azione operativa?",
    options: ["Interrompere trasfusione e valutare", "Continuare e ignorare", "Aumentare velocità", "Rimuovere ago"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Sospetta reazione: stop e valutazione; mantenere accesso con fisiologica secondo setting.",
  },
  {
    id: "q1129",
    q: "Quale parametro è più utile per valutare efficacia della diuresi in paziente cateterizzato?",
    options: ["mL/kg/h", "Numero di passi", "Ore di sonno", "Dolore"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "La diuresi si valuta spesso in mL/kg/h e trend nel tempo.",
  },
  {
    id: "q1130",
    q: "Quale è il rischio principale di un catetere vescicale mantenuto senza indicazione?",
    options: ["IVU/CAUTI", "Iperglicemia", "Iperkaliemia", "Ipertensione"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Catetere inutile aumenta rischio di infezione urinaria associata a catetere (CAUTI).",
  },
  {
    id: "q1131",
    q: "Quale associazione può aumentare rischio di sanguinamento gastrointestinale?",
    options: ["FANS + corticosteroide", "Paracetamolo + soluzione fisiologica", "Vitamina C + acqua", "Amoxicillina + yogurt"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "FANS con corticosteroidi (o anticoagulanti) aumenta rischio GI; valutare gastroprotezione secondo indicazione.",
  },
  {
    id: "q1132",
    q: "Quale è una causa frequente di ipotensione ortostatica?",
    options: ["Disidratazione/diuretici", "Aumento appetito", "Allergia al lattice", "Ipervitaminosi"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "Disidratazione, diuretici e vasodilatatori possono favorire ipotensione ortostatica.",
  },
  {
    id: "q1133",
    q: "Quale segno può suggerire sovraccarico di fluidi?",
    options: ["Crepitii polmonari e edema", "Cute secca", "Miosi", "Prurito isolato"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Crepitii, edema declive, aumento peso e peggioramento dispnea suggeriscono overload.",
  },
  {
    id: "q1134",
    q: "Quale antibiotico è più associato a rischio di colite da C. difficile (in generale)?",
    options: ["Clindamicina", "Azitromicina", "Penicillina V", "Fosfomicina"],
    answer: 0,
    category: "antibiotici",
    difficulty: "medium",
    explain: "Molti antibiotici possono predisporre a C. difficile; clindamicina è un classico farmaco ad alto rischio.",
  },
  {
    id: "q1135",
    q: "In caso di convulsione in atto: quale è una priorità infermieristica?",
    options: ["Proteggere il paziente da traumi e garantire pervietà vie aeree", "Bloccare arti", "Mettere oggetti in bocca", "Lasciare il paziente da solo"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Protezione da traumi, tempo crisi, vie aeree e chiamata supporto; evitare oggetti in bocca e contenimento pericoloso.",
  },
  {
    id: "q1136",
    q: "Quale parametro è utile per valutare risposta a ossigenoterapia in fase acuta?",
    options: ["SpO₂ + clinica (FR, lavoro respiratorio)", "Solo temperatura", "Solo peso", "Solo dolore"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "Valuta saturazione ma anche clinica: FR, dispnea, uso muscoli accessori, stato mentale.",
  },
  {
    id: "q1137",
    q: "Quale è un rischio della somministrazione rapida di magnesio EV?",
    options: ["Ipotensione e flushing", "Iperglicemia", "Ipernatriemia", "Tachicardia sempre"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Magnesio EV troppo rapido può dare ipotensione/flushing: infondere secondo prescrizione.",
  },
  {
    id: "q1138",
    q: "Quale misura riduce il rischio di contaminazione durante medicazione di CVC?",
    options: ["Campo sterile e disinfezione corretta", "Aprire il set e lasciarlo sul letto", "Toccare la punta del catetere", "Non usare guanti"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Tecnica asettica e campo sterile riducono contaminazioni durante manipolazioni del CVC.",
  },
  {
    id: "q1139",
    q: "In paziente con BPCO ipercapnica nota, quale target SpO₂ è spesso usato?",
    options: ["88–92%", "96–100%", "70–75%", "Sempre 100%"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "In BPCO con ipercapnia: spesso target 88–92% per evitare iperossia (personalizzare e seguire protocolli locali).",
  },
  {
    id: "q1140",
    q: "Quale intervento è corretto se un paziente riferisce prurito e orticaria subito dopo un antibiotico EV?",
    options: ["Interrompere infusione e valutare/avvisare", "Continuare più veloce", "Somministrare altra dose", "Dimettere subito"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Sospetta reazione: stop, valutazione ABC, avvisa medico e gestisci secondo protocollo.",
  },
  {
    id: "q1141",
    q: "Quale è una regola pratica sicura per la compatibilità in Y-site se il dato non è disponibile?",
    options: ["Preferire linea dedicata o flush", "Mescolare comunque", "Aumentare concentrazione", "Usare sempre bicarbonato"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Se non hai dato di compatibilità: linea dedicata/flush riduce rischi.",
  },
  {
    id: "q1142",
    q: "Quale parametro è un indicatore di gravità nella sepsi (trend)?",
    options: ["Lattato (se disponibile) e perfusione", "Colore occhi", "Altezza", "Età"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Trend lattato e segni di ipoperfusione aiutano a stratificare gravità e risposta al trattamento.",
  },
  {
    id: "q1143",
    q: "Quale indicazione è corretta per il controllo del sito di accesso EV?",
    options: ["Valutare regolarmente dolore, arrossamento, edema", "Controllare solo a fine turno", "Mai documentare", "Coprire sempre senza vedere"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Monitoraggio del sito riduce complicanze (flebite, infiltrazione, stravaso).",
  },
  {
    id: "q1144",
    q: "Quale farmaco è tipicamente vescicante/irritante e richiede attenzione al sito?",
    options: ["Norepinefrina", "Paracetamolo", "Metoclopramide orale", "Vitamina B12"],
    answer: 0,
    category: "farmaci",
    difficulty: "medium",
    explain: "Vasopressori sono irritanti: preferire accesso centrale se possibile e monitorare sito/estravaso.",
  },
  {
    id: "q1145",
    q: "Quale è un segno di ipercapnia (CO₂ alta) più tipico?",
    options: ["Sonnolenza/confusione", "Cute fredda", "Poliuria", "Ittero"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Ipercapnia può dare cefalea, sonnolenza, confusione e asterixis; rivaluta ventilazione.",
  },
  {
    id: "q1146",
    q: "Quale antibiotico richiede spesso infusione lenta e diluizione adeguata per tollerabilità venosa?",
    options: ["Vancomicina", "Amoxicillina orale", "Doxiciclina orale", "Metronidazolo gel"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "Vancomicina EV: infusione controllata riduce reazioni da velocità e irritazione venosa.",
  },
  {
    id: "q1147",
    q: "Paziente con saturazione buona ma dispnea importante: quale step è sensato?",
    options: ["Valutare FR/lavoro respiratorio e altre cause", "Ignorare perché SpO₂ è ok", "Dimettere", "Solo acqua"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Dispnea può essere da cause non ipossiemiche (acidosi, ansia, scompenso, embolia): serve valutazione completa.",
  },
  {
    id: "q1148",
    q: "Quale è una buona pratica per la sicurezza nella somministrazione farmaci EV?",
    options: ["Doppio controllo per farmaci ad alto rischio", "Saltare sempre l'etichetta", "Non verificare la prescrizione", "Usare dosi a memoria"],
    answer: 0,
    category: "procedure",
    difficulty: "easy",
    explain: "Farmaci high-alert: doppio controllo e tracciabilità riducono errori.",
  },
  {
    id: "q1149",
    q: "Quale antibiotico può richiedere aggiustamento in insufficienza renale (molti casi)?",
    options: ["Meropenem", "Eritromicina topica", "Rifamicina spray", "Clotrimazolo crema"],
    answer: 0,
    category: "antibiotici",
    difficulty: "easy",
    explain: "Molti beta-lattamici (es. meropenem) richiedono aggiustamento dose su funzione renale.",
  },
  {
    id: "q1150",
    q: "Quale azione è corretta quando un paziente riferisce improvvisa dispnea e dolore toracico pleuritico?",
    options: ["Valutare ABCDE e attivare escalation", "Aspettare 2 ore", "Solo analgesico e a casa", "Far camminare"],
    answer: 0,
    category: "emergenza",
    difficulty: "hard",
    explain: "Dispnea acuta + dolore pleuritico è red flag (es. embolia/pneumotorace): valutazione e escalation immediata.",
  },
  {
    id: "q1151",
    q: "In un paziente con CVC, quale segno locale è più suggestivo di infezione correlata al catetere?",
    options: ["Cute integra senza dolore", "Eritema e dolore lungo il tragitto", "Bruciore in sede di prelievo capillare", "Edema declive bilaterale"],
    answer: 1,
    category: "procedure",
    difficulty: "easy",
    explain: "Eritema, dolore, calore o essudato in sede/tragitto sono segni locali di possibile infezione CVC.",
  },
  {
    id: "q1152",
    q: "Prima di eseguire un’emogasanalisi arteriosa, quale controllo è raccomandato (se applicabile)?",
    options: ["Test di Allen", "Test di Romberg", "Test di Trendelenburg", "Test di Lasègue"],
    answer: 0,
    category: "emogas",
    difficulty: "easy",
    explain: "Il test di Allen valuta la pervietà del circolo collaterale (radiale/ulnare) prima del prelievo arterioso.",
  },
  {
    id: "q1153",
    q: "Quale parametro dell’emogas è più direttamente utile per valutare la ventilazione alveolare?",
    options: ["PaO₂", "SaO₂", "PaCO₂", "HCO₃⁻"],
    answer: 2,
    category: "emogas",
    difficulty: "easy",
    explain: "La PaCO₂ riflette la ventilazione alveolare: aumenta con ipoventilazione e diminuisce con iperventilazione.",
  },
  {
    id: "q1154",
    q: "In caso di sospetta sepsi, quale set di azioni iniziali è più appropriato?",
    options: ["Attendere esiti colturali prima di antibiotico", "Valutare ABC, lattato, emocolture e avvio terapia secondo percorso locale", "Solo fluidi senza monitoraggio", "Somministrare diuretico"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Approccio early: valutazione rapida, lattato, emocolture e avvio trattamento secondo percorsi locali (incl. antibiotico/fluido) quando indicato.",
  },
  {
    id: "q1155",
    q: "Quale valore è più coerente con alcalosi respiratoria acuta?",
    options: ["pH alto e PaCO₂ bassa", "pH basso e HCO₃⁻ basso", "pH basso e PaCO₂ alta", "pH normale e PaCO₂ normale"],
    answer: 0,
    category: "emogas",
    difficulty: "medium",
    explain: "Nell’alcalosi respiratoria acuta aumenta il pH e diminuisce la PaCO₂; il compenso metabolico è minimo inizialmente.",
  },
  {
    id: "q1156",
    q: "Durante ossigenoterapia con maschera Venturi, cosa determina la FiO₂ erogata?",
    options: ["La pressione arteriosa", "Il colore/ugello Venturi e il flusso impostato", "La frequenza cardiaca", "Il calibro dell’ago"],
    answer: 1,
    category: "ossigeno",
    difficulty: "easy",
    explain: "La maschera Venturi fornisce FiO₂ controllata tramite ugello e flusso indicato dal produttore.",
  },
  {
    id: "q1157",
    q: "Quale situazione è una red flag per ipossia tissutale nonostante SpO₂ normale?",
    options: ["Paziente con COHb elevata (intossicazione da CO)", "Paziente con febbre", "Paziente con ipertensione", "Paziente con cataratta"],
    answer: 0,
    category: "ossigeno",
    difficulty: "medium",
    explain: "La COHb falsamente aumenta la SpO₂; serve valutazione clinica ed emogas/COHb.",
  },
  {
    id: "q1158",
    q: "In un paziente con dolore toracico e dispnea improvvisa, quale dato clinico richiede escalation immediata?",
    options: ["Sat 98% in aria ambiente", "Tachicardia e ipotensione", "Polso regolare a 70 bpm", "Temperatura 36,5°C"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Dispnea + instabilità emodinamica è red flag: valutazione e gestione urgente secondo percorsi locali.",
  },
  {
    id: "q1159",
    q: "Qual è l’obiettivo principale del lavaggio (flush) tra infusioni incompatibili sulla stessa linea?",
    options: ["Aumentare la glicemia", "Prevenire precipitati e interazioni in linea", "Ridurre la pressione arteriosa", "Aumentare la diuresi"],
    answer: 1,
    category: "infusioni",
    difficulty: "easy",
    explain: "Il flush riduce il contatto tra soluzioni incompatibili nella stessa linea, prevenendo precipitati/occlusioni.",
  },
  {
    id: "q1160",
    q: "Quale misura riduce il rischio di errori nella preparazione di infusioni ad alto rischio?",
    options: ["Preparare senza etichetta", "Doppio controllo e etichettatura chiara con concentrazione e velocità", "Usare solo memoria", "Cambiare siringhe durante infusione"],
    answer: 1,
    category: "sicurezza",
    difficulty: "medium",
    explain: "Doppio controllo e label standard (farmaco, dose, concentrazione, velocità, data/ora) riducono errori.",
  },
  {
    id: "q1161",
    q: "In caso di stravaso da accesso periferico, qual è l’azione iniziale più corretta?",
    options: ["Aumentare la velocità di infusione", "Interrompere l’infusione e valutare secondo protocollo locale", "Applicare calore sempre", "Rimuovere subito l’ago senza altre azioni"],
    answer: 1,
    category: "procedure",
    difficulty: "medium",
    explain: "In genere si interrompe l’infusione, si valuta il sito e si segue il percorso locale (farmaco specifico, impacchi, antidoti).",
  },
  {
    id: "q1162",
    q: "Quale tubo è più usato per emocromo (CBC) nella maggior parte dei laboratori?",
    options: ["Tappo verde (eparina)", "Tappo viola/ lilla (EDTA)", "Tappo rosso (siero)", "Tappo grigio (fluoruro)"],
    answer: 1,
    category: "laboratorio",
    difficulty: "easy",
    explain: "L’EDTA è l’anticoagulante tipico per emocromo.",
  },
  {
    id: "q1163",
    q: "Perché spesso l’emocromo non è la prima provetta se si usa il butterfly?",
    options: ["Perché è sempre contaminato", "Perché la linea può contenere aria: si usa una provetta di scarto per riempire il tubing se necessario", "Perché non serve mai", "Perché coagula sempre"],
    answer: 1,
    category: "laboratorio",
    difficulty: "medium",
    explain: "Con butterfly può essere utile una provetta di scarto per riempire il tubing e garantire il corretto rapporto sangue/additivo.",
  },
  {
    id: "q1164",
    q: "Quale parametro indica più direttamente il deficit di base/compenso metabolico all’emogas?",
    options: ["PaO₂", "Base excess (BE)", "SaO₂", "EtCO₂"],
    answer: 1,
    category: "emogas",
    difficulty: "medium",
    explain: "Il BE riflette la componente metabolica (acidosi/alcalosi metabolica e compensi).",
  },
  {
    id: "q1165",
    q: "Quale azione riduce il rischio di cadute in un paziente confuso che tenta di alzarsi?",
    options: ["Lasciare sponde sempre alte e basta", "Valutazione rischio, chiamata a portata, sorveglianza e ausili secondo procedura", "Spegnere le luci", "Limitare liquidi"],
    answer: 1,
    category: "assistenza",
    difficulty: "easy",
    explain: "Misure multifattoriali (valutazione, ambiente, sorveglianza, ausili) sono più efficaci e sicure.",
  },
  {
    id: "q1166",
    q: "In un paziente con sospetta ipoglicemia, qual è il primo passo?",
    options: ["Somministrare insulina rapida", "Misurare glicemia capillare e valutare stato di coscienza", "Eseguire ECG", "Somministrare diuretico"],
    answer: 1,
    category: "emergenza",
    difficulty: "easy",
    explain: "Con sintomi compatibili: controllo glicemia e trattamento rapido secondo condizioni cliniche.",
  },
  {
    id: "q1167",
    q: "Quale scala è più usata per valutare sedazione in terapia intensiva?",
    options: ["RASS", "Braden", "Morse", "Charlson"],
    answer: 0,
    category: "scale",
    difficulty: "medium",
    explain: "La RASS (Richmond Agitation-Sedation Scale) è ampiamente utilizzata per sedazione/agitation in ICU.",
  },
  {
    id: "q1168",
    q: "Quale intervento è più appropriato per prevenire lesioni da pressione in paziente allettato?",
    options: ["Mobilizzazione regolare e valutazione cute, presidi antidecubito quando indicato", "Solo crema profumata", "Sponde alte", "Restrizione liquidi"],
    answer: 0,
    category: "assistenza",
    difficulty: "easy",
    explain: "Prevenzione LdP: repositioning, valutazione rischio, supporti, gestione umidità/nutrizione secondo indicazione.",
  },
  {
    id: "q1169",
    q: "Cosa indica una SaO₂ bassa con PaO₂ normale in presenza di metaemoglobinemia?",
    options: ["Errore di calibrazione della bilancia", "Dissociazione tra misure: possibile disemoglobinemia", "Iperventilazione", "Ipotermia"],
    answer: 1,
    category: "ossigeno",
    difficulty: "hard",
    explain: "Le disemoglobinemie possono alterare saturazioni; la PaO₂ può risultare normale mentre la saturazione misurata è bassa.",
  },
  {
    id: "q1170",
    q: "Quale è un segno precoce di deterioramento clinico nei sistemi early warning (es. NEWS2)?",
    options: ["Miglioramento appetito", "Aumento FR e alterazione stato mentale", "Unghie lunghe", "Dolore cronico stabile"],
    answer: 1,
    category: "scale",
    difficulty: "medium",
    explain: "Tachipnea e alterazione coscienza sono indicatori precoci frequenti di deterioramento.",
  },
  {
    id: "q1171",
    q: "Quale approccio è corretto per una terapia antibiotica EV: tempi e monitoraggio?",
    options: ["Somministrare quando possibile senza orario", "Rispettare tempi di somministrazione, monitorare reazioni e compatibilità", "Somministrare solo di notte", "Non serve monitorare"],
    answer: 1,
    category: "farmaci",
    difficulty: "easy",
    explain: "Timing e monitoraggio (allergie, reazioni, accesso, compatibilità) sono essenziali per sicurezza ed efficacia.",
  },
  {
    id: "q1172",
    q: "In caso di reazione anafilattica, quale intervento è prioritario secondo pratica clinica comune?",
    options: ["Adrenalina IM e valutazione ABC con chiamata ai soccorsi", "Solo antistaminico orale", "Solo cortisone EV", "Attendere regressione spontanea"],
    answer: 0,
    category: "emergenza",
    difficulty: "hard",
    explain: "Adrenalina IM è trattamento di prima linea, con gestione ABC e attivazione percorso emergenza.",
  },
  {
    id: "q1173",
    q: "Quale indicazione è corretta per la maschera non-rebreather (reservoir)?",
    options: ["FiO₂ bassa e precisa", "FiO₂ alta in emergenza, con reservoir gonfio e flusso adeguato", "Solo per ossigeno a 1 L/min", "Solo per aerosol"],
    answer: 1,
    category: "ossigeno",
    difficulty: "medium",
    explain: "NRB per alti flussi/FiO₂ elevata: reservoir deve restare gonfio con flusso adeguato.",
  },
  {
    id: "q1174",
    q: "Qual è un effetto atteso dell’iperventilazione in un paziente senza patologia metabolica?",
    options: ["Aumento PaCO₂", "Diminuzione PaCO₂ e aumento pH", "Diminuzione pH", "Aumento lattato sempre"],
    answer: 1,
    category: "emogas",
    difficulty: "easy",
    explain: "Iperventilazione → elimina CO₂ → PaCO₂↓ e pH↑ (alcalosi respiratoria).",
  },
  {
    id: "q1175",
    q: "Quale controllo è utile prima di somministrare eparina a basso peso molecolare?",
    options: ["Pressione oculare", "Piastrine e rischio emorragico (quando indicato)", "Colesterolo", "Vista"],
    answer: 1,
    category: "farmaci",
    difficulty: "medium",
    explain: "Valutare rischio sanguinamento, piastrine e indicazioni/controindicazioni (es. HIT, procedure) secondo scenario.",
  },
  {
    id: "q1176",
    q: "Nella gestione di una linea EV, quale misura riduce il rischio di occlusione?",
    options: ["Non lavare mai", "Flush appropriato e clamp corretto quando indicato", "Piegare il deflussore", "Usare solo soluzioni ipertoniche"],
    answer: 1,
    category: "infusioni",
    difficulty: "easy",
    explain: "Flush e gestione corretta del clamp/linea aiutano a prevenire occlusioni e residui.",
  },
  {
    id: "q1177",
    q: "Quale parametro clinico è più indicativo di perfusione periferica ridotta?",
    options: ["Riempimento capillare prolungato", "Capelli lucidi", "Tono della voce", "Scoliosi"],
    answer: 0,
    category: "emergenza",
    difficulty: "easy",
    explain: "CRT prolungato può indicare ipoperfusione; va interpretato nel contesto clinico.",
  },
  {
    id: "q1178",
    q: "Perché è importante confermare l’identità del paziente prima di una procedura?",
    options: ["Per formalità", "Per prevenire errori di paziente, terapia o procedura", "Per aumentare la velocità", "Non è importante"],
    answer: 1,
    category: "sicurezza",
    difficulty: "easy",
    explain: "Identificazione corretta riduce errori gravi (farmaci, trasfusioni, procedure).",
  },
  {
    id: "q1179",
    q: "Quale comportamento è corretto nella somministrazione di farmaci ad alto rischio (es. insulina EV)?",
    options: ["Preparare senza verifiche", "Usare check-list/doppio controllo e pompa infusionale quando indicato", "Usare sempre bolo rapido", "Somministrare senza etichetta"],
    answer: 1,
    category: "sicurezza",
    difficulty: "medium",
    explain: "Farmaci ad alto rischio richiedono controlli aggiuntivi e dispositivi sicuri (pompa/standard).",
  },
  {
    id: "q1180",
    q: "In un paziente con dispnea e sibilo, quale misura è utile per valutare gravità?",
    options: ["Scala di Glasgow", "FR, uso muscoli accessori, SpO₂ e peak flow se disponibile", "Test di Allen", "Indice di massa corporea"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Segni di lavoro respiratorio e SpO₂ aiutano a stimare la gravità e guidare escalation.",
  },
  {
    id: "q1181",
    q: "Quale segno può indicare sovraccarico di volume dopo fluidi rapidi?",
    options: ["Miglioramento diuresi", "Crepitii polmonari e aumento dispnea", "Riduzione pressione venosa", "Cute secca"],
    answer: 1,
    category: "emergenza",
    difficulty: "medium",
    explain: "Crepitii/dispnea possono indicare congestione: rivalutare e adattare terapia.",
  },
  {
    id: "q1182",
    q: "Nel prelievo venoso, perché evitare di lasciare il laccio emostatico troppo a lungo?",
    options: ["Per non spaventare", "Può alterare alcuni analiti e aumentare emolisi/concentrazione", "Perché non serve mai", "Per aumentare il flusso"],
    answer: 1,
    category: "laboratorio",
    difficulty: "easy",
    explain: "Stasi prolungata può influenzare analiti e qualità del campione.",
  },
  {
    id: "q1183",
    q: "Quale è una misura di prevenzione delle infezioni correlata a cateteri urinari?",
    options: ["Mantenere circuito chiuso e sacchetto sotto livello vescica", "Aprire spesso il circuito", "Tenere sacchetto sul letto", "Irrigazione routinaria"],
    answer: 0,
    category: "procedure",
    difficulty: "medium",
    explain: "Circuito chiuso e drenaggio corretto riducono rischio di CAUTI.",
  },
  {
    id: "q1184",
    q: "In un paziente con iperkaliemia severa con alterazioni ECG, cosa è prioritario?",
    options: ["Calcio EV per stabilizzare membrana + gestione secondo percorso locale", "Solo acqua", "Solo paracetamolo", "Attendere il giorno dopo"],
    answer: 0,
    category: "emergenza",
    difficulty: "hard",
    explain: "Il calcio EV stabilizza la membrana miocardica in iperkaliemia con segni ECG, insieme alle altre misure.",
  },
  {
    id: "q1185",
    q: "Quale è un segno tipico di ipoventilazione?",
    options: ["PaCO₂ bassa", "PaCO₂ alta", "pH alto sempre", "HCO₃⁻ basso sempre"],
    answer: 1,
    category: "emogas",
    difficulty: "easy",
    explain: "Ipoventilazione → ritenzione CO₂ → PaCO₂ aumenta.",
  },
  {
    id: "q1186",
    q: "Quale intervento è appropriato per ridurre la contaminazione in emocoltura?",
    options: ["Palpare dopo disinfezione", "Disinfezione accurata e rispetto tempi di asciugatura, tecnica sterile", "Usare garza asciutta senza antisettico", "Riempire poco"],
    answer: 1,
    category: "laboratorio",
    difficulty: "medium",
    explain: "La corretta antisepsi e tecnica riducono contaminazioni che falsano esiti.",
  },
  {
    id: "q1187",
    q: "Quale indicazione è più corretta per la gestione del dolore post-operatorio?",
    options: ["Ignorare il dolore", "Valutare con scala, somministrare analgesia prescritta e rivalutare efficacia", "Solo ghiaccio sempre", "Solo sedazione"],
    answer: 1,
    category: "assistenza",
    difficulty: "easy",
    explain: "Valutazione sistematica e rivalutazione post-intervento analgesico migliorano outcome e sicurezza.",
  },
  {
    id: "q1188",
    q: "Cosa significa quando un farmaco è “incompatibile in Y-site” con un altro?",
    options: ["Possono essere miscelati liberamente", "Non dovrebbero co-infondere sulla stessa Y senza separazione/flush", "Devono essere dati insieme", "Significa stesso produttore"],
    answer: 1,
    category: "infusioni",
    difficulty: "easy",
    explain: "Incompatibilità in Y-site → rischio precipitati/degradazione: usare linee separate o flush e sequenza.",
  },
  {
    id: "q1189",
    q: "Quale misura è utile per prevenire errori con abbreviazioni pericolose (es. U, IU)?",
    options: ["Usarle sempre", "Evitare abbreviazioni non standard e scrivere per esteso", "Scrivere a matita", "Usare solo emoji"],
    answer: 1,
    category: "sicurezza",
    difficulty: "medium",
    explain: "Abbreviazioni ambigue aumentano errori; scrivere per esteso è più sicuro.",
  },
  {
    id: "q1190",
    q: "Nel monitoraggio di un paziente con NIV, quale parametro è importante rivalutare frequentemente?",
    options: ["Colore occhi", "SpO₂, FR, comfort e segni di affaticamento", "Lunghezza capelli", "Temperatura della stanza"],
    answer: 1,
    category: "ossigeno",
    difficulty: "medium",
    explain: "In NIV vanno rivalutati scambi, lavoro respiratorio, tolleranza e segni di fallimento/peggioramento.",
  },
  {
    id: "q1191",
    q: "Quale è una controindicazione relativa alla puntura arteriosa radiale?",
    options: ["Ipertensione lieve", "Circolo collaterale insufficiente al test di Allen", "Febbre", "Bradicardia"],
    answer: 1,
    category: "emogas",
    difficulty: "hard",
    explain: "Allen negativo (collaterale insufficiente) aumenta rischio ischemia locale: valutare alternativa.",
  },
  {
    id: "q1192",
    q: "Quale segno può indicare disidratazione in un anziano fragile?",
    options: ["Mucose secche e ipotensione ortostatica", "Aumento peso improvviso", "Edemi importanti", "Dispnea parossistica notturna"],
    answer: 0,
    category: "assistenza",
    difficulty: "medium",
    explain: "Segni clinici come mucose secche e ortostatismo possono suggerire disidratazione (valutare contesto).",
  },
  {
    id: "q1193",
    q: "Quale pratica è corretta per la conservazione di campioni ematici quando richiesto?",
    options: ["Lasciarli al sole", "Seguire indicazioni (temperatura/tempo) e inviare rapidamente", "Agitarli vigorosamente sempre", "Congelarli sempre"],
    answer: 1,
    category: "laboratorio",
    difficulty: "medium",
    explain: "Tempo/temperatura influenzano stabilità analiti; seguire indicazioni del laboratorio.",
  },
  {
    id: "q1194",
    q: "Qual è la priorità nella gestione iniziale di un paziente con GCS in calo?",
    options: ["Solo glicemia", "Valutazione ABCDE, glicemia, e attivazione escalation secondo percorso locale", "Solo saturazione", "Solo pressione"],
    answer: 1,
    category: "emergenza",
    difficulty: "hard",
    explain: "Calo GCS è red flag: approccio ABCDE, cause reversibili (es. glicemia) ed escalation.",
  },
  {
    id: "q1195",
    q: "Quale segno suggerisce possibile embolia polmonare?",
    options: ["Dolore pleuritico, dispnea improvvisa, tachicardia", "Prurito cronico", "Dolore lombare da 6 mesi", "Rinite"],
    answer: 0,
    category: "emergenza",
    difficulty: "medium",
    explain: "Triade/associazione di dispnea improvvisa, tachicardia e dolore pleuritico è suggestiva (contesto).",
  },
  {
    id: "q1196",
    q: "Quale intervento è utile nella prevenzione delle infezioni correlate a ventilazione (VAP)?",
    options: ["Testa letto sollevata quando indicato e igiene orale", "Sedazione profonda continua sempre", "Aspiratione senza indicazione", "Umidificare senza controllo"],
    answer: 0,
    category: "assistenza",
    difficulty: "medium",
    explain: "Head-of-bed elevation e oral care sono misure preventive riconosciute in bundle VAP.",
  },
  {
    id: "q1197",
    q: "Nel paziente in terapia con warfarin, quale parametro laboratoristico è usato per monitoraggio?",
    options: ["PT/INR", "aPTT", "Troponina", "Amilasi"],
    answer: 0,
    category: "farmaci",
    difficulty: "easy",
    explain: "Il warfarin si monitora con PT/INR.",
  },
  {
    id: "q1198",
    q: "Quale è la sequenza più sicura nella somministrazione di KCl EV?",
    options: ["Bolo rapido", "Solo in infusione controllata e diluita, mai bolo, con pompa", "Intramuscolo", "Per os sempre"],
    answer: 1,
    category: "farmaci",
    difficulty: "hard",
    explain: "KCl EV è ad alto rischio: mai bolo, solo diluito e con pompa/monitoraggio secondo indicazioni.",
  },
  {
    id: "q1199",
    q: "In un paziente con nausea importante, quale informazione è utile prima di antiemetico?",
    options: ["Numero scarpe", "Possibile causa e farmaci assunti, allergie", "Colore preferito", "Segno zodiacale"],
    answer: 1,
    category: "farmaci",
    difficulty: "easy",
    explain: "Valutare causa, terapie in corso e allergie per scelta sicura dell’antiemetico.",
  },
  {
    id: "q1200",
    q: "Quale dato suggerisce acidosi metabolica?",
    options: ["pH basso e HCO₃⁻ basso", "pH alto e PaCO₂ bassa", "pH alto e HCO₃⁻ alto", "PaO₂ alta"],
    answer: 0,
    category: "emogas",
    difficulty: "medium",
    explain: "Acidosi metabolica: pH↓ e bicarbonati↓ (con compenso respiratorio possibile).",
  },
];
