import type { QuizQuestion } from "@/features/cards/quiz/quizBank";
// Extra university bank: 150 domande
export const QUIZ_BANK_ANATOMY_EXTRA: QuizQuestion[] = [
  {
    id: "uni_an_0501",
    q: "[Anatomia] Domanda 501: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0502",
    q: "[Anatomia] Domanda 502: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0503",
    q: "[Anatomia] Domanda 503: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0504",
    q: "[Anatomia] Domanda 504: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0505",
    q: "[Anatomia] Domanda 505: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0506",
    q: "[Anatomia] Domanda 506: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0507",
    q: "[Anatomia] Domanda 507: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0508",
    q: "[Anatomia] Domanda 508: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0509",
    q: "[Anatomia] Domanda 509: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0510",
    q: "[Anatomia] Domanda 510: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0511",
    q: "[Anatomia] Domanda 511: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0512",
    q: "[Anatomia] Domanda 512: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0513",
    q: "[Anatomia] Domanda 513: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0514",
    q: "[Anatomia] Domanda 514: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0515",
    q: "[Anatomia] Domanda 515: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0516",
    q: "[Anatomia] Domanda 516: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0517",
    q: "[Anatomia] Domanda 517: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0518",
    q: "[Anatomia] Domanda 518: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0519",
    q: "[Anatomia] Domanda 519: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0520",
    q: "[Anatomia] Domanda 520: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0521",
    q: "[Anatomia] Domanda 521: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0522",
    q: "[Anatomia] Domanda 522: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0523",
    q: "[Anatomia] Domanda 523: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0524",
    q: "[Anatomia] Domanda 524: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0525",
    q: "[Anatomia] Domanda 525: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0526",
    q: "[Anatomia] Domanda 526: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0527",
    q: "[Anatomia] Domanda 527: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0528",
    q: "[Anatomia] Domanda 528: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0529",
    q: "[Anatomia] Domanda 529: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0530",
    q: "[Anatomia] Domanda 530: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0531",
    q: "[Anatomia] Domanda 531: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0532",
    q: "[Anatomia] Domanda 532: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0533",
    q: "[Anatomia] Domanda 533: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0534",
    q: "[Anatomia] Domanda 534: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0535",
    q: "[Anatomia] Domanda 535: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0536",
    q: "[Anatomia] Domanda 536: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0537",
    q: "[Anatomia] Domanda 537: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0538",
    q: "[Anatomia] Domanda 538: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0539",
    q: "[Anatomia] Domanda 539: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0540",
    q: "[Anatomia] Domanda 540: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0541",
    q: "[Anatomia] Domanda 541: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0542",
    q: "[Anatomia] Domanda 542: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0543",
    q: "[Anatomia] Domanda 543: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0544",
    q: "[Anatomia] Domanda 544: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0545",
    q: "[Anatomia] Domanda 545: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0546",
    q: "[Anatomia] Domanda 546: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0547",
    q: "[Anatomia] Domanda 547: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0548",
    q: "[Anatomia] Domanda 548: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0549",
    q: "[Anatomia] Domanda 549: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0550",
    q: "[Anatomia] Domanda 550: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0551",
    q: "[Anatomia] Domanda 551: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0552",
    q: "[Anatomia] Domanda 552: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0553",
    q: "[Anatomia] Domanda 553: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0554",
    q: "[Anatomia] Domanda 554: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0555",
    q: "[Anatomia] Domanda 555: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0556",
    q: "[Anatomia] Domanda 556: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0557",
    q: "[Anatomia] Domanda 557: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0558",
    q: "[Anatomia] Domanda 558: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0559",
    q: "[Anatomia] Domanda 559: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0560",
    q: "[Anatomia] Domanda 560: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0561",
    q: "[Anatomia] Domanda 561: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0562",
    q: "[Anatomia] Domanda 562: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0563",
    q: "[Anatomia] Domanda 563: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0564",
    q: "[Anatomia] Domanda 564: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0565",
    q: "[Anatomia] Domanda 565: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0566",
    q: "[Anatomia] Domanda 566: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0567",
    q: "[Anatomia] Domanda 567: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0568",
    q: "[Anatomia] Domanda 568: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0569",
    q: "[Anatomia] Domanda 569: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0570",
    q: "[Anatomia] Domanda 570: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0571",
    q: "[Anatomia] Domanda 571: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0572",
    q: "[Anatomia] Domanda 572: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0573",
    q: "[Anatomia] Domanda 573: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0574",
    q: "[Anatomia] Domanda 574: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0575",
    q: "[Anatomia] Domanda 575: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0576",
    q: "[Anatomia] Domanda 576: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0577",
    q: "[Anatomia] Domanda 577: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0578",
    q: "[Anatomia] Domanda 578: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0579",
    q: "[Anatomia] Domanda 579: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0580",
    q: "[Anatomia] Domanda 580: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0581",
    q: "[Anatomia] Domanda 581: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0582",
    q: "[Anatomia] Domanda 582: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0583",
    q: "[Anatomia] Domanda 583: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0584",
    q: "[Anatomia] Domanda 584: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0585",
    q: "[Anatomia] Domanda 585: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0586",
    q: "[Anatomia] Domanda 586: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0587",
    q: "[Anatomia] Domanda 587: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0588",
    q: "[Anatomia] Domanda 588: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0589",
    q: "[Anatomia] Domanda 589: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0590",
    q: "[Anatomia] Domanda 590: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0591",
    q: "[Anatomia] Domanda 591: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0592",
    q: "[Anatomia] Domanda 592: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0593",
    q: "[Anatomia] Domanda 593: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0594",
    q: "[Anatomia] Domanda 594: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0595",
    q: "[Anatomia] Domanda 595: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0596",
    q: "[Anatomia] Domanda 596: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0597",
    q: "[Anatomia] Domanda 597: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0598",
    q: "[Anatomia] Domanda 598: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0599",
    q: "[Anatomia] Domanda 599: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0600",
    q: "[Anatomia] Domanda 600: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0601",
    q: "[Anatomia] Domanda 601: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0602",
    q: "[Anatomia] Domanda 602: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0603",
    q: "[Anatomia] Domanda 603: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0604",
    q: "[Anatomia] Domanda 604: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0605",
    q: "[Anatomia] Domanda 605: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0606",
    q: "[Anatomia] Domanda 606: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0607",
    q: "[Anatomia] Domanda 607: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0608",
    q: "[Anatomia] Domanda 608: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0609",
    q: "[Anatomia] Domanda 609: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0610",
    q: "[Anatomia] Domanda 610: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0611",
    q: "[Anatomia] Domanda 611: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0612",
    q: "[Anatomia] Domanda 612: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0613",
    q: "[Anatomia] Domanda 613: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0614",
    q: "[Anatomia] Domanda 614: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0615",
    q: "[Anatomia] Domanda 615: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0616",
    q: "[Anatomia] Domanda 616: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0617",
    q: "[Anatomia] Domanda 617: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0618",
    q: "[Anatomia] Domanda 618: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0619",
    q: "[Anatomia] Domanda 619: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0620",
    q: "[Anatomia] Domanda 620: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0621",
    q: "[Anatomia] Domanda 621: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0622",
    q: "[Anatomia] Domanda 622: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0623",
    q: "[Anatomia] Domanda 623: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0624",
    q: "[Anatomia] Domanda 624: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0625",
    q: "[Anatomia] Domanda 625: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0626",
    q: "[Anatomia] Domanda 626: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0627",
    q: "[Anatomia] Domanda 627: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0628",
    q: "[Anatomia] Domanda 628: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0629",
    q: "[Anatomia] Domanda 629: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0630",
    q: "[Anatomia] Domanda 630: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0631",
    q: "[Anatomia] Domanda 631: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0632",
    q: "[Anatomia] Domanda 632: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0633",
    q: "[Anatomia] Domanda 633: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0634",
    q: "[Anatomia] Domanda 634: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0635",
    q: "[Anatomia] Domanda 635: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0636",
    q: "[Anatomia] Domanda 636: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0637",
    q: "[Anatomia] Domanda 637: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0638",
    q: "[Anatomia] Domanda 638: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0639",
    q: "[Anatomia] Domanda 639: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0640",
    q: "[Anatomia] Domanda 640: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0641",
    q: "[Anatomia] Domanda 641: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0642",
    q: "[Anatomia] Domanda 642: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0643",
    q: "[Anatomia] Domanda 643: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0644",
    q: "[Anatomia] Domanda 644: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0645",
    q: "[Anatomia] Domanda 645: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0646",
    q: "[Anatomia] Domanda 646: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0647",
    q: "[Anatomia] Domanda 647: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0648",
    q: "[Anatomia] Domanda 648: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0649",
    q: "[Anatomia] Domanda 649: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_an_0650",
    q: "[Anatomia] Domanda 650: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "anatomia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
];
