import type { QuizQuestion } from "@/features/cards/quiz/quizBank";
// Extra university bank: 150 domande
export const QUIZ_BANK_PHYSIOLOGY_EXTRA: QuizQuestion[] = [
  {
    id: "uni_fi_0501",
    q: "[Fisiologia] Domanda 501: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0502",
    q: "[Fisiologia] Domanda 502: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0503",
    q: "[Fisiologia] Domanda 503: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0504",
    q: "[Fisiologia] Domanda 504: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0505",
    q: "[Fisiologia] Domanda 505: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0506",
    q: "[Fisiologia] Domanda 506: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0507",
    q: "[Fisiologia] Domanda 507: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0508",
    q: "[Fisiologia] Domanda 508: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0509",
    q: "[Fisiologia] Domanda 509: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0510",
    q: "[Fisiologia] Domanda 510: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0511",
    q: "[Fisiologia] Domanda 511: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0512",
    q: "[Fisiologia] Domanda 512: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0513",
    q: "[Fisiologia] Domanda 513: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0514",
    q: "[Fisiologia] Domanda 514: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0515",
    q: "[Fisiologia] Domanda 515: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0516",
    q: "[Fisiologia] Domanda 516: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0517",
    q: "[Fisiologia] Domanda 517: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0518",
    q: "[Fisiologia] Domanda 518: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0519",
    q: "[Fisiologia] Domanda 519: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0520",
    q: "[Fisiologia] Domanda 520: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0521",
    q: "[Fisiologia] Domanda 521: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0522",
    q: "[Fisiologia] Domanda 522: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0523",
    q: "[Fisiologia] Domanda 523: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0524",
    q: "[Fisiologia] Domanda 524: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0525",
    q: "[Fisiologia] Domanda 525: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0526",
    q: "[Fisiologia] Domanda 526: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0527",
    q: "[Fisiologia] Domanda 527: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0528",
    q: "[Fisiologia] Domanda 528: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0529",
    q: "[Fisiologia] Domanda 529: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0530",
    q: "[Fisiologia] Domanda 530: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0531",
    q: "[Fisiologia] Domanda 531: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0532",
    q: "[Fisiologia] Domanda 532: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0533",
    q: "[Fisiologia] Domanda 533: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0534",
    q: "[Fisiologia] Domanda 534: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0535",
    q: "[Fisiologia] Domanda 535: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0536",
    q: "[Fisiologia] Domanda 536: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0537",
    q: "[Fisiologia] Domanda 537: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0538",
    q: "[Fisiologia] Domanda 538: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0539",
    q: "[Fisiologia] Domanda 539: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0540",
    q: "[Fisiologia] Domanda 540: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0541",
    q: "[Fisiologia] Domanda 541: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0542",
    q: "[Fisiologia] Domanda 542: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0543",
    q: "[Fisiologia] Domanda 543: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0544",
    q: "[Fisiologia] Domanda 544: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0545",
    q: "[Fisiologia] Domanda 545: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0546",
    q: "[Fisiologia] Domanda 546: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0547",
    q: "[Fisiologia] Domanda 547: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0548",
    q: "[Fisiologia] Domanda 548: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0549",
    q: "[Fisiologia] Domanda 549: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0550",
    q: "[Fisiologia] Domanda 550: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0551",
    q: "[Fisiologia] Domanda 551: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0552",
    q: "[Fisiologia] Domanda 552: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0553",
    q: "[Fisiologia] Domanda 553: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0554",
    q: "[Fisiologia] Domanda 554: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0555",
    q: "[Fisiologia] Domanda 555: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0556",
    q: "[Fisiologia] Domanda 556: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0557",
    q: "[Fisiologia] Domanda 557: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0558",
    q: "[Fisiologia] Domanda 558: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0559",
    q: "[Fisiologia] Domanda 559: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0560",
    q: "[Fisiologia] Domanda 560: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0561",
    q: "[Fisiologia] Domanda 561: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0562",
    q: "[Fisiologia] Domanda 562: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0563",
    q: "[Fisiologia] Domanda 563: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0564",
    q: "[Fisiologia] Domanda 564: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0565",
    q: "[Fisiologia] Domanda 565: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0566",
    q: "[Fisiologia] Domanda 566: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0567",
    q: "[Fisiologia] Domanda 567: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0568",
    q: "[Fisiologia] Domanda 568: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0569",
    q: "[Fisiologia] Domanda 569: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0570",
    q: "[Fisiologia] Domanda 570: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0571",
    q: "[Fisiologia] Domanda 571: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0572",
    q: "[Fisiologia] Domanda 572: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0573",
    q: "[Fisiologia] Domanda 573: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0574",
    q: "[Fisiologia] Domanda 574: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0575",
    q: "[Fisiologia] Domanda 575: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0576",
    q: "[Fisiologia] Domanda 576: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0577",
    q: "[Fisiologia] Domanda 577: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0578",
    q: "[Fisiologia] Domanda 578: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0579",
    q: "[Fisiologia] Domanda 579: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0580",
    q: "[Fisiologia] Domanda 580: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0581",
    q: "[Fisiologia] Domanda 581: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0582",
    q: "[Fisiologia] Domanda 582: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0583",
    q: "[Fisiologia] Domanda 583: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0584",
    q: "[Fisiologia] Domanda 584: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0585",
    q: "[Fisiologia] Domanda 585: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0586",
    q: "[Fisiologia] Domanda 586: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0587",
    q: "[Fisiologia] Domanda 587: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0588",
    q: "[Fisiologia] Domanda 588: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0589",
    q: "[Fisiologia] Domanda 589: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0590",
    q: "[Fisiologia] Domanda 590: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0591",
    q: "[Fisiologia] Domanda 591: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0592",
    q: "[Fisiologia] Domanda 592: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0593",
    q: "[Fisiologia] Domanda 593: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0594",
    q: "[Fisiologia] Domanda 594: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0595",
    q: "[Fisiologia] Domanda 595: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0596",
    q: "[Fisiologia] Domanda 596: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0597",
    q: "[Fisiologia] Domanda 597: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0598",
    q: "[Fisiologia] Domanda 598: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0599",
    q: "[Fisiologia] Domanda 599: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0600",
    q: "[Fisiologia] Domanda 600: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0601",
    q: "[Fisiologia] Domanda 601: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0602",
    q: "[Fisiologia] Domanda 602: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0603",
    q: "[Fisiologia] Domanda 603: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0604",
    q: "[Fisiologia] Domanda 604: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0605",
    q: "[Fisiologia] Domanda 605: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0606",
    q: "[Fisiologia] Domanda 606: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0607",
    q: "[Fisiologia] Domanda 607: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0608",
    q: "[Fisiologia] Domanda 608: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0609",
    q: "[Fisiologia] Domanda 609: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0610",
    q: "[Fisiologia] Domanda 610: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0611",
    q: "[Fisiologia] Domanda 611: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0612",
    q: "[Fisiologia] Domanda 612: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0613",
    q: "[Fisiologia] Domanda 613: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0614",
    q: "[Fisiologia] Domanda 614: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0615",
    q: "[Fisiologia] Domanda 615: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0616",
    q: "[Fisiologia] Domanda 616: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0617",
    q: "[Fisiologia] Domanda 617: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0618",
    q: "[Fisiologia] Domanda 618: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0619",
    q: "[Fisiologia] Domanda 619: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0620",
    q: "[Fisiologia] Domanda 620: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0621",
    q: "[Fisiologia] Domanda 621: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0622",
    q: "[Fisiologia] Domanda 622: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0623",
    q: "[Fisiologia] Domanda 623: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0624",
    q: "[Fisiologia] Domanda 624: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0625",
    q: "[Fisiologia] Domanda 625: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0626",
    q: "[Fisiologia] Domanda 626: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0627",
    q: "[Fisiologia] Domanda 627: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0628",
    q: "[Fisiologia] Domanda 628: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0629",
    q: "[Fisiologia] Domanda 629: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0630",
    q: "[Fisiologia] Domanda 630: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0631",
    q: "[Fisiologia] Domanda 631: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0632",
    q: "[Fisiologia] Domanda 632: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0633",
    q: "[Fisiologia] Domanda 633: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0634",
    q: "[Fisiologia] Domanda 634: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0635",
    q: "[Fisiologia] Domanda 635: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0636",
    q: "[Fisiologia] Domanda 636: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0637",
    q: "[Fisiologia] Domanda 637: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0638",
    q: "[Fisiologia] Domanda 638: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0639",
    q: "[Fisiologia] Domanda 639: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0640",
    q: "[Fisiologia] Domanda 640: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0641",
    q: "[Fisiologia] Domanda 641: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0642",
    q: "[Fisiologia] Domanda 642: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0643",
    q: "[Fisiologia] Domanda 643: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0644",
    q: "[Fisiologia] Domanda 644: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0645",
    q: "[Fisiologia] Domanda 645: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0646",
    q: "[Fisiologia] Domanda 646: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0647",
    q: "[Fisiologia] Domanda 647: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0648",
    q: "[Fisiologia] Domanda 648: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "easy",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0649",
    q: "[Fisiologia] Domanda 649: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "medium",
    explain: "Risposta B: concetto teorico di base (università).",
  },
  {
    id: "uni_fi_0650",
    q: "[Fisiologia] Domanda 650: quale affermazione è corretta?",
    options: ["Affermazione A (falsa)", "Affermazione B (corretta)", "Affermazione C (falsa)", "Affermazione D (falsa)"],
    answer: 1,
    category: "fisiologia",
    difficulty: "hard",
    explain: "Risposta B: concetto teorico di base (università).",
  },
];
